import "dotenv/config";
import { PrismaLibSql } from "@prisma/adapter-libsql";
import { PrismaClient } from "../prisma/generated/client";

const databaseUrl = process.env.DATABASE_URL || "file:./dev.db";
const adapter = new PrismaLibSql({ url: databaseUrl });
const prisma = new PrismaClient({ adapter });

interface VehicleData {
  brand: { name: string; country: string };
  model: { name: string; startYear: number };
  version: {
    name: string;
    engine: string;
    horsepower: number;
    transmission: string;
    fuel: string;
    price: number;
    currency: string;
    country: string;
    source: string;
  };
}

const allVehiclePrices: VehicleData[] = [
  // RENAULT
  {
    brand: { name: "Renault", country: "Fransa" },
    model: { name: "Clio", startYear: 2025 },
    version: {
      name: "1.0 SCE Life",
      engine: "1.0L",
      horsepower: 65,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 899000,
      currency: "TRY",
      country: "TR",
      source: "Renault Türkiye",
    },
  },
  {
    brand: { name: "Renault", country: "Fransa" },
    model: { name: "Clio", startYear: 2025 },
    version: {
      name: "1.0 TCE Joy",
      engine: "1.0L Turbo",
      horsepower: 90,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1179000,
      currency: "TRY",
      country: "TR",
      source: "Renault Türkiye",
    },
  },
  {
    brand: { name: "Renault", country: "Fransa" },
    model: { name: "Clio", startYear: 2025 },
    version: {
      name: "1.0 TCE Evolution",
      engine: "1.0L Turbo",
      horsepower: 100,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1349000,
      currency: "TRY",
      country: "TR",
      source: "Renault Türkiye",
    },
  },
  {
    brand: { name: "Renault", country: "Fransa" },
    model: { name: "Megane", startYear: 2025 },
    version: {
      name: "1.3 TCE Joy",
      engine: "1.3L Turbo",
      horsepower: 130,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1399000,
      currency: "TRY",
      country: "TR",
      source: "Renault Türkiye",
    },
  },
  {
    brand: { name: "Renault", country: "Fransa" },
    model: { name: "Megane", startYear: 2025 },
    version: {
      name: "1.3 TCE Evolution",
      engine: "1.3L Turbo",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1599000,
      currency: "TRY",
      country: "TR",
      source: "Renault Türkiye",
    },
  },
  {
    brand: { name: "Renault", country: "Fransa" },
    model: { name: "Austral", startYear: 2025 },
    version: {
      name: "1.2 TCE Mild Hybrid",
      engine: "1.2L Hybrid",
      horsepower: 140,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 1899000,
      currency: "TRY",
      country: "TR",
      source: "Renault Türkiye",
    },
  },
  {
    brand: { name: "Renault", country: "Fransa" },
    model: { name: "Austral", startYear: 2025 },
    version: {
      name: "1.2 TCE E-Tech",
      engine: "1.2L Hybrid",
      horsepower: 200,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 2299000,
      currency: "TRY",
      country: "TR",
      source: "Renault Türkiye",
    },
  },
  {
    brand: { name: "Renault", country: "Fransa" },
    model: { name: "Symbioz", startYear: 2025 },
    version: {
      name: "1.2 TCE E-Tech",
      engine: "1.2L Hybrid",
      horsepower: 140,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 1699000,
      currency: "TRY",
      country: "TR",
      source: "Renault Türkiye",
    },
  },
  {
    brand: { name: "Renault", country: "Fransa" },
    model: { name: "Captur", startYear: 2025 },
    version: {
      name: "1.0 TCE Joy",
      engine: "1.0L Turbo",
      horsepower: 90,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1299000,
      currency: "TRY",
      country: "TR",
      source: "Renault Türkiye",
    },
  },
  {
    brand: { name: "Renault", country: "Fransa" },
    model: { name: "Arkana", startYear: 2025 },
    version: {
      name: "1.3 TCE E-Tech",
      engine: "1.3L Hybrid",
      horsepower: 140,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 1899000,
      currency: "TRY",
      country: "TR",
      source: "Renault Türkiye",
    },
  },

  // FIAT
  {
    brand: { name: "Fiat", country: "İtalya" },
    model: { name: "Topolino", startYear: 2025 },
    version: {
      name: "6 kW/8 HP",
      engine: "Elektrik",
      horsepower: 8,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 605900,
      currency: "TRY",
      country: "TR",
      source: "Fiat Türkiye",
    },
  },
  {
    brand: { name: "Fiat", country: "İtalya" },
    model: { name: "500e", startYear: 2025 },
    version: {
      name: "42 kW",
      engine: "Elektrik",
      horsepower: 118,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 1299000,
      currency: "TRY",
      country: "TR",
      source: "Fiat Türkiye",
    },
  },
  {
    brand: { name: "Fiat", country: "İtalya" },
    model: { name: "Panda", startYear: 2025 },
    version: {
      name: "1.0 Fire",
      engine: "1.0L",
      horsepower: 69,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 699000,
      currency: "TRY",
      country: "TR",
      source: "Fiat Türkiye",
    },
  },
  {
    brand: { name: "Fiat", country: "İtalya" },
    model: { name: "Egea Sedan", startYear: 2025 },
    version: {
      name: "1.4 Fire Easy",
      engine: "1.4L",
      horsepower: 95,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 1184900,
      currency: "TRY",
      country: "TR",
      source: "Fiat Türkiye",
    },
  },
  {
    brand: { name: "Fiat", country: "İtalya" },
    model: { name: "Egea Sedan", startYear: 2025 },
    version: {
      name: "1.4 Fire Lounge",
      engine: "1.4L",
      horsepower: 95,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1349000,
      currency: "TRY",
      country: "TR",
      source: "Fiat Türkiye",
    },
  },
  {
    brand: { name: "Fiat", country: "İtalya" },
    model: { name: "Egea Cross", startYear: 2025 },
    version: {
      name: "1.4 Fire Street",
      engine: "1.4L",
      horsepower: 95,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 1270520,
      currency: "TRY",
      country: "TR",
      source: "Fiat Türkiye",
    },
  },
  {
    brand: { name: "Fiat", country: "İtalya" },
    model: { name: "Egea Cross", startYear: 2025 },
    version: {
      name: "1.4 Fire Lounge",
      engine: "1.4L",
      horsepower: 95,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1449000,
      currency: "TRY",
      country: "TR",
      source: "Fiat Türkiye",
    },
  },
  {
    brand: { name: "Fiat", country: "İtalya" },
    model: { name: "Grande Panda", startYear: 2025 },
    version: {
      name: "1.2 Hybrid",
      engine: "1.2L Hybrid",
      horsepower: 100,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 1449900,
      currency: "TRY",
      country: "TR",
      source: "Fiat Türkiye",
    },
  },
  {
    brand: { name: "Fiat", country: "İtalya" },
    model: { name: "Doblo", startYear: 2025 },
    version: {
      name: "1.2 Easy",
      engine: "1.2L",
      horsepower: 80,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 1159000,
      currency: "TRY",
      country: "TR",
      source: "Fiat Türkiye",
    },
  },
  {
    brand: { name: "Fiat", country: "İtalya" },
    model: { name: "Doblo", startYear: 2025 },
    version: {
      name: "1.6 Multijet",
      engine: "1.6L Dizel",
      horsepower: 120,
      transmission: "Manuel",
      fuel: "Dizel",
      price: 1399000,
      currency: "TRY",
      country: "TR",
      source: "Fiat Türkiye",
    },
  },

  // TOYOTA
  {
    brand: { name: "Toyota", country: "Japonya" },
    model: { name: "Yaris", startYear: 2025 },
    version: {
      name: "1.5 Hybrid",
      engine: "1.5L Hybrid",
      horsepower: 120,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 1349000,
      currency: "TRY",
      country: "TR",
      source: "Toyota Türkiye",
    },
  },
  {
    brand: { name: "Toyota", country: "Japonya" },
    model: { name: "Yaris", startYear: 2025 },
    version: {
      name: "1.5 Hybrid GR Sport",
      engine: "1.5L Hybrid",
      horsepower: 130,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 1599000,
      currency: "TRY",
      country: "TR",
      source: "Toyota Türkiye",
    },
  },
  {
    brand: { name: "Toyota", country: "Japonya" },
    model: { name: "Corolla", startYear: 2025 },
    version: {
      name: "1.5 Hybrid Dream",
      engine: "1.5L Hybrid",
      horsepower: 120,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 1549000,
      currency: "TRY",
      country: "TR",
      source: "Toyota Türkiye",
    },
  },
  {
    brand: { name: "Toyota", country: "Japonya" },
    model: { name: "Corolla", startYear: 2025 },
    version: {
      name: "1.5 Hybrid GR Sport",
      engine: "1.5L Hybrid",
      horsepower: 130,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 1749000,
      currency: "TRY",
      country: "TR",
      source: "Toyota Türkiye",
    },
  },
  {
    brand: { name: "Toyota", country: "Japonya" },
    model: { name: "Corolla", startYear: 2025 },
    version: {
      name: "2.0 Hybrid Adventure",
      engine: "2.0L Hybrid",
      horsepower: 180,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 1999000,
      currency: "TRY",
      country: "TR",
      source: "Toyota Türkiye",
    },
  },
  {
    brand: { name: "Toyota", country: "Japonya" },
    model: { name: "C-HR", startYear: 2025 },
    version: {
      name: "1.8 Hybrid Dream",
      engine: "1.8L Hybrid",
      horsepower: 140,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 1699000,
      currency: "TRY",
      country: "TR",
      source: "Toyota Türkiye",
    },
  },
  {
    brand: { name: "Toyota", country: "Japonya" },
    model: { name: "C-HR", startYear: 2025 },
    version: {
      name: "2.0 Hybrid GR Sport",
      engine: "2.0L Hybrid",
      horsepower: 180,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 2199000,
      currency: "TRY",
      country: "TR",
      source: "Toyota Türkiye",
    },
  },
  {
    brand: { name: "Toyota", country: "Japonya" },
    model: { name: "RAV4", startYear: 2025 },
    version: {
      name: "2.0 Hybrid Adventure",
      engine: "2.0L Hybrid",
      horsepower: 180,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 2699000,
      currency: "TRY",
      country: "TR",
      source: "Toyota Türkiye",
    },
  },
  {
    brand: { name: "Toyota", country: "Japonya" },
    model: { name: "RAV4", startYear: 2025 },
    version: {
      name: "2.5 Hybrid Luxury",
      engine: "2.5L Hybrid",
      horsepower: 220,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 3299000,
      currency: "TRY",
      country: "TR",
      source: "Toyota Türkiye",
    },
  },
  {
    brand: { name: "Toyota", country: "Japonya" },
    model: { name: "Land Cruiser", startYear: 2025 },
    version: {
      name: "2.8 D-4D",
      engine: "2.8L Dizel",
      horsepower: 200,
      transmission: "Otomatik",
      fuel: "Dizel",
      price: 4699000,
      currency: "TRY",
      country: "TR",
      source: "Toyota Türkiye",
    },
  },

  // VOLKSWAGEN
  {
    brand: { name: "Volkswagen", country: "Almanya" },
    model: { name: "Polo", startYear: 2025 },
    version: {
      name: "1.0 TSI Life",
      engine: "1.0L Turbo",
      horsepower: 95,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1299000,
      currency: "TRY",
      country: "TR",
      source: "Volkswagen Türkiye",
    },
  },
  {
    brand: { name: "Volkswagen", country: "Almanya" },
    model: { name: "Polo", startYear: 2025 },
    version: {
      name: "1.0 TSI Style",
      engine: "1.0L Turbo",
      horsepower: 110,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1499000,
      currency: "TRY",
      country: "TR",
      source: "Volkswagen Türkiye",
    },
  },
  {
    brand: { name: "Volkswagen", country: "Almanya" },
    model: { name: "Golf", startYear: 2025 },
    version: {
      name: "1.5 TSI Life",
      engine: "1.5L Turbo",
      horsepower: 130,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1549000,
      currency: "TRY",
      country: "TR",
      source: "Volkswagen Türkiye",
    },
  },
  {
    brand: { name: "Volkswagen", country: "Almanya" },
    model: { name: "Golf", startYear: 2025 },
    version: {
      name: "1.5 TSI Style",
      engine: "1.5L Turbo",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1799000,
      currency: "TRY",
      country: "TR",
      source: "Volkswagen Türkiye",
    },
  },
  {
    brand: { name: "Volkswagen", country: "Almanya" },
    model: { name: "Golf", startYear: 2025 },
    version: {
      name: "2.0 TDI Style",
      engine: "2.0L Dizel",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Dizel",
      price: 1999000,
      currency: "TRY",
      country: "TR",
      source: "Volkswagen Türkiye",
    },
  },
  {
    brand: { name: "Volkswagen", country: "Almanya" },
    model: { name: "T-Roc", startYear: 2025 },
    version: {
      name: "1.5 TSI Life",
      engine: "1.5L Turbo",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1799000,
      currency: "TRY",
      country: "TR",
      source: "Volkswagen Türkiye",
    },
  },
  {
    brand: { name: "Volkswagen", country: "Almanya" },
    model: { name: "T-Roc", startYear: 2025 },
    version: {
      name: "2.0 TSI 4Motion",
      engine: "2.0L Turbo",
      horsepower: 190,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 2299000,
      currency: "TRY",
      country: "TR",
      source: "Volkswagen Türkiye",
    },
  },
  {
    brand: { name: "Volkswagen", country: "Almanya" },
    model: { name: "Tiguan", startYear: 2025 },
    version: {
      name: "1.5 TSI Life",
      engine: "1.5L Turbo",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 2099000,
      currency: "TRY",
      country: "TR",
      source: "Volkswagen Türkiye",
    },
  },
  {
    brand: { name: "Volkswagen", country: "Almanya" },
    model: { name: "Tiguan", startYear: 2025 },
    version: {
      name: "2.0 TDI 4Motion",
      engine: "2.0L Dizel",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Dizel",
      price: 2499000,
      currency: "TRY",
      country: "TR",
      source: "Volkswagen Türkiye",
    },
  },
  {
    brand: { name: "Volkswagen", country: "Almanya" },
    model: { name: "Passat", startYear: 2025 },
    version: {
      name: "1.5 TSI Life",
      engine: "1.5L Turbo",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1999000,
      currency: "TRY",
      country: "TR",
      source: "Volkswagen Türkiye",
    },
  },

  // HYUNDAI
  {
    brand: { name: "Hyundai", country: "Güney Kore" },
    model: { name: "i10", startYear: 2025 },
    version: {
      name: "1.2 MPI Select",
      engine: "1.2L",
      horsepower: 83,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 699000,
      currency: "TRY",
      country: "TR",
      source: "Hyundai Türkiye",
    },
  },
  {
    brand: { name: "Hyundai", country: "Güney Kore" },
    model: { name: "i10", startYear: 2025 },
    version: {
      name: "1.2 MPI Style",
      engine: "1.2L",
      horsepower: 83,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 849000,
      currency: "TRY",
      country: "TR",
      source: "Hyundai Türkiye",
    },
  },
  {
    brand: { name: "Hyundai", country: "Güney Kore" },
    model: { name: "i20", startYear: 2025 },
    version: {
      name: "1.4 MPI Select",
      engine: "1.4L",
      horsepower: 100,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 899000,
      currency: "TRY",
      country: "TR",
      source: "Hyundai Türkiye",
    },
  },
  {
    brand: { name: "Hyundai", country: "Güney Kore" },
    model: { name: "i20", startYear: 2025 },
    version: {
      name: "1.4 MPI Style",
      engine: "1.4L",
      horsepower: 100,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1049000,
      currency: "TRY",
      country: "TR",
      source: "Hyundai Türkiye",
    },
  },
  {
    brand: { name: "Hyundai", country: "Güney Kore" },
    model: { name: "i20", startYear: 2025 },
    version: {
      name: "1.0 T-GDI N Line",
      engine: "1.0L Turbo",
      horsepower: 120,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1249000,
      currency: "TRY",
      country: "TR",
      source: "Hyundai Türkiye",
    },
  },
  {
    brand: { name: "Hyundai", country: "Güney Kore" },
    model: { name: "Tucson", startYear: 2025 },
    version: {
      name: "1.6 TGDI",
      engine: "1.6L Turbo",
      horsepower: 160,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1899000,
      currency: "TRY",
      country: "TR",
      source: "Hyundai Türkiye",
    },
  },
  {
    brand: { name: "Hyundai", country: "Güney Kore" },
    model: { name: "Tucson", startYear: 2025 },
    version: {
      name: "1.6 CRDi",
      engine: "1.6L Dizel",
      horsepower: 136,
      transmission: "Otomatik",
      fuel: "Dizel",
      price: 2099000,
      currency: "TRY",
      country: "TR",
      source: "Hyundai Türkiye",
    },
  },
  {
    brand: { name: "Hyundai", country: "Güney Kore" },
    model: { name: "Santa Fe", startYear: 2025 },
    version: {
      name: "2.2 CRDi",
      engine: "2.2L Dizel",
      horsepower: 194,
      transmission: "Otomatik",
      fuel: "Dizel",
      price: 3499000,
      currency: "TRY",
      country: "TR",
      source: "Hyundai Türkiye",
    },
  },
  {
    brand: { name: "Hyundai", country: "Güney Kore" },
    model: { name: "Kona", startYear: 2025 },
    version: {
      name: "1.0 T-GDI",
      engine: "1.0L Turbo",
      horsepower: 120,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1349000,
      currency: "TRY",
      country: "TR",
      source: "Hyundai Türkiye",
    },
  },
  {
    brand: { name: "Hyundai", country: "Güney Kore" },
    model: { name: "Kona Electric", startYear: 2025 },
    version: {
      name: "48 kWh",
      engine: "Elektrik",
      horsepower: 156,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 1799000,
      currency: "TRY",
      country: "TR",
      source: "Hyundai Türkiye",
    },
  },

  // PEUGEOT
  {
    brand: { name: "Peugeot", country: "Fransa" },
    model: { name: "208", startYear: 2025 },
    version: {
      name: "1.2 PureTech Active",
      engine: "1.2L Turbo",
      horsepower: 100,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1099000,
      currency: "TRY",
      country: "TR",
      source: "Peugeot Türkiye",
    },
  },
  {
    brand: { name: "Peugeot", country: "Fransa" },
    model: { name: "208", startYear: 2025 },
    version: {
      name: "1.2 PureTech Allure",
      engine: "1.2L Turbo",
      horsepower: 130,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1299000,
      currency: "TRY",
      country: "TR",
      source: "Peugeot Türkiye",
    },
  },
  {
    brand: { name: "Peugeot", country: "Fransa" },
    model: { name: "308", startYear: 2025 },
    version: {
      name: "1.2 PureTech Active",
      engine: "1.2L Turbo",
      horsepower: 130,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1399000,
      currency: "TRY",
      country: "TR",
      source: "Peugeot Türkiye",
    },
  },
  {
    brand: { name: "Peugeot", country: "Fransa" },
    model: { name: "308", startYear: 2025 },
    version: {
      name: "1.5 BlueHDi",
      engine: "1.5L Dizel",
      horsepower: 130,
      transmission: "Otomatik",
      fuel: "Dizel",
      price: 1599000,
      currency: "TRY",
      country: "TR",
      source: "Peugeot Türkiye",
    },
  },
  {
    brand: { name: "Peugeot", country: "Fransa" },
    model: { name: "2008", startYear: 2025 },
    version: {
      name: "1.2 PureTech Active",
      engine: "1.2L Turbo",
      horsepower: 100,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1249000,
      currency: "TRY",
      country: "TR",
      source: "Peugeot Türkiye",
    },
  },
  {
    brand: { name: "Peugeot", country: "Fransa" },
    model: { name: "2008", startYear: 2025 },
    version: {
      name: "1.2 PureTech Allure",
      engine: "1.2L Turbo",
      horsepower: 130,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1449000,
      currency: "TRY",
      country: "TR",
      source: "Peugeot Türkiye",
    },
  },
  {
    brand: { name: "Peugeot", country: "Fransa" },
    model: { name: "3008", startYear: 2025 },
    version: {
      name: "1.2 PureTech GT",
      engine: "1.2L Turbo",
      horsepower: 130,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1899000,
      currency: "TRY",
      country: "TR",
      source: "Peugeot Türkiye",
    },
  },
  {
    brand: { name: "Peugeot", country: "Fransa" },
    model: { name: "5008", startYear: 2025 },
    version: {
      name: "1.2 PureTech GT",
      engine: "1.2L Turbo",
      horsepower: 130,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 2199000,
      currency: "TRY",
      country: "TR",
      source: "Peugeot Türkiye",
    },
  },
  {
    brand: { name: "Peugeot", country: "Fransa" },
    model: { name: "408", startYear: 2025 },
    version: {
      name: "1.2 PureTech GT",
      engine: "1.2L Turbo",
      horsepower: 130,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1699000,
      currency: "TRY",
      country: "TR",
      source: "Peugeot Türkiye",
    },
  },
  {
    brand: { name: "Peugeot", country: "Fransa" },
    model: { name: "508", startYear: 2025 },
    version: {
      name: "1.6 PureTech GT",
      engine: "1.6L Turbo",
      horsepower: 215,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 2699000,
      currency: "TRY",
      country: "TR",
      source: "Peugeot Türkiye",
    },
  },

  // FORD
  {
    brand: { name: "Ford", country: "ABD" },
    model: { name: "Fiesta", startYear: 2025 },
    version: {
      name: "1.1 Ti-VCT",
      engine: "1.1L",
      horsepower: 75,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 699000,
      currency: "TRY",
      country: "TR",
      source: "Ford Türkiye",
    },
  },
  {
    brand: { name: "Ford", country: "ABD" },
    model: { name: "Puma", startYear: 2025 },
    version: {
      name: "1.0 EcoBoost Titanium",
      engine: "1.0L Turbo",
      horsepower: 125,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1514000,
      currency: "TRY",
      country: "TR",
      source: "Ford Türkiye",
    },
  },
  {
    brand: { name: "Ford", country: "ABD" },
    model: { name: "Puma", startYear: 2025 },
    version: {
      name: "1.0 EcoBoost ST",
      engine: "1.0L Turbo",
      horsepower: 155,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1799000,
      currency: "TRY",
      country: "TR",
      source: "Ford Türkiye",
    },
  },
  {
    brand: { name: "Ford", country: "ABD" },
    model: { name: "Focus", startYear: 2025 },
    version: {
      name: "1.0 EcoBoost Titanium",
      engine: "1.0L Turbo",
      horsepower: 125,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1399000,
      currency: "TRY",
      country: "TR",
      source: "Ford Türkiye",
    },
  },
  {
    brand: { name: "Ford", country: "ABD" },
    model: { name: "Focus", startYear: 2025 },
    version: {
      name: "2.0 EcoBlue",
      engine: "2.0L Dizel",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Dizel",
      price: 1699000,
      currency: "TRY",
      country: "TR",
      source: "Ford Türkiye",
    },
  },
  {
    brand: { name: "Ford", country: "ABD" },
    model: { name: "Kuga", startYear: 2025 },
    version: {
      name: "1.5 EcoBoost Titanium",
      engine: "1.5L Turbo",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1799000,
      currency: "TRY",
      country: "TR",
      source: "Ford Türkiye",
    },
  },
  {
    brand: { name: "Ford", country: "ABD" },
    model: { name: "Kuga", startYear: 2025 },
    version: {
      name: "2.0 EcoBlue",
      engine: "2.0L Dizel",
      horsepower: 190,
      transmission: "Otomatik",
      fuel: "Dizel",
      price: 2199000,
      currency: "TRY",
      country: "TR",
      source: "Ford Türkiye",
    },
  },
  {
    brand: { name: "Ford", country: "ABD" },
    model: { name: "Explorer", startYear: 2025 },
    version: {
      name: "2.0 EcoBlue",
      engine: "2.0L Dizel",
      horsepower: 190,
      transmission: "Otomatik",
      fuel: "Dizel",
      price: 2499000,
      currency: "TRY",
      country: "TR",
      source: "Ford Türkiye",
    },
  },
  {
    brand: { name: "Ford", country: "ABD" },
    model: { name: "Explorer EV", startYear: 2025 },
    version: {
      name: "Select",
      engine: "Elektrik",
      horsepower: 170,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 1720000,
      currency: "TRY",
      country: "TR",
      source: "Ford Türkiye",
    },
  },
  {
    brand: { name: "Ford", country: "ABD" },
    model: { name: "Mustang", startYear: 2025 },
    version: {
      name: "2.3 EcoBoost",
      engine: "2.3L Turbo",
      horsepower: 304,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 3499000,
      currency: "TRY",
      country: "TR",
      source: "Ford Türkiye",
    },
  },

  // DACIA
  {
    brand: { name: "Dacia", country: "Romanya" },
    model: { name: "Sandero", startYear: 2025 },
    version: {
      name: "1.0 TCe Essential",
      engine: "1.0L Turbo",
      horsepower: 90,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 749000,
      currency: "TRY",
      country: "TR",
      source: "Dacia Türkiye",
    },
  },
  {
    brand: { name: "Dacia", country: "Romanya" },
    model: { name: "Sandero", startYear: 2025 },
    version: {
      name: "1.0 TCe Expression",
      engine: "1.0L Turbo",
      horsepower: 90,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 899000,
      currency: "TRY",
      country: "TR",
      source: "Dacia Türkiye",
    },
  },
  {
    brand: { name: "Dacia", country: "Romanya" },
    model: { name: "Sandero Stepway", startYear: 2025 },
    version: {
      name: "1.0 TCe Expression",
      engine: "1.0L Turbo",
      horsepower: 90,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 999000,
      currency: "TRY",
      country: "TR",
      source: "Dacia Türkiye",
    },
  },
  {
    brand: { name: "Dacia", country: "Romanya" },
    model: { name: "Sandero Stepway", startYear: 2025 },
    version: {
      name: "1.0 TCe Extreme",
      engine: "1.0L Turbo",
      horsepower: 100,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1313000,
      currency: "TRY",
      country: "TR",
      source: "Dacia Türkiye",
    },
  },
  {
    brand: { name: "Dacia", country: "Romanya" },
    model: { name: "Jogger", startYear: 2025 },
    version: {
      name: "1.0 TCe Essential",
      engine: "1.0L Turbo",
      horsepower: 100,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 999000,
      currency: "TRY",
      country: "TR",
      source: "Dacia Türkiye",
    },
  },
  {
    brand: { name: "Dacia", country: "Romanya" },
    model: { name: "Jogger", startYear: 2025 },
    version: {
      name: "1.0 TCe Extreme Eco-G",
      engine: "1.0L Turbo",
      horsepower: 100,
      transmission: "Manuel",
      fuel: "Benzin/LPG",
      price: 1492000,
      currency: "TRY",
      country: "TR",
      source: "Dacia Türkiye",
    },
  },
  {
    brand: { name: "Dacia", country: "Romanya" },
    model: { name: "Duster", startYear: 2025 },
    version: {
      name: "1.0 TCe 4x2",
      engine: "1.0L Turbo",
      horsepower: 100,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 1199000,
      currency: "TRY",
      country: "TR",
      source: "Dacia Türkiye",
    },
  },
  {
    brand: { name: "Dacia", country: "Romanya" },
    model: { name: "Duster", startYear: 2025 },
    version: {
      name: "1.0 TCe 4x4",
      engine: "1.0L Turbo",
      horsepower: 125,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 1645000,
      currency: "TRY",
      country: "TR",
      source: "Dacia Türkiye",
    },
  },
  {
    brand: { name: "Dacia", country: "Romanya" },
    model: { name: "Duster", startYear: 2025 },
    version: {
      name: "1.6 SCe 4x4",
      engine: "1.6L",
      horsepower: 105,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 1499000,
      currency: "TRY",
      country: "TR",
      source: "Dacia Türkiye",
    },
  },
  {
    brand: { name: "Dacia", country: "Romanya" },
    model: { name: "Spring", startYear: 2025 },
    version: {
      name: "Electric",
      engine: "Elektrik",
      horsepower: 45,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 799000,
      currency: "TRY",
      country: "TR",
      source: "Dacia Türkiye",
    },
  },

  // KIA
  {
    brand: { name: "Kia", country: "Güney Kore" },
    model: { name: "Picanto", startYear: 2025 },
    version: {
      name: "1.2 MT",
      engine: "1.2L",
      horsepower: 84,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 699000,
      currency: "TRY",
      country: "TR",
      source: "Kia Türkiye",
    },
  },
  {
    brand: { name: "Kia", country: "Güney Kore" },
    model: { name: "Picanto", startYear: 2025 },
    version: {
      name: "1.2 AT",
      engine: "1.2L",
      horsepower: 84,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 849000,
      currency: "TRY",
      country: "TR",
      source: "Kia Türkiye",
    },
  },
  {
    brand: { name: "Kia", country: "Güney Kore" },
    model: { name: "Rio", startYear: 2025 },
    version: {
      name: "1.4 MT",
      engine: "1.4L",
      horsepower: 100,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 899000,
      currency: "TRY",
      country: "TR",
      source: "Kia Türkiye",
    },
  },
  {
    brand: { name: "Kia", country: "Güney Kore" },
    model: { name: "Rio", startYear: 2025 },
    version: {
      name: "1.4 AT",
      engine: "1.4L",
      horsepower: 100,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1049000,
      currency: "TRY",
      country: "TR",
      source: "Kia Türkiye",
    },
  },
  {
    brand: { name: "Kia", country: "Güney Kore" },
    model: { name: "Stonic", startYear: 2025 },
    version: {
      name: "1.4 MT",
      engine: "1.4L",
      horsepower: 100,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 1049000,
      currency: "TRY",
      country: "TR",
      source: "Kia Türkiye",
    },
  },
  {
    brand: { name: "Kia", country: "Güney Kore" },
    model: { name: "Stonic", startYear: 2025 },
    version: {
      name: "1.0 T-GDI",
      engine: "1.0L Turbo",
      horsepower: 120,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1249000,
      currency: "TRY",
      country: "TR",
      source: "Kia Türkiye",
    },
  },
  {
    brand: { name: "Kia", country: "Güney Kore" },
    model: { name: "Sportage", startYear: 2025 },
    version: {
      name: "1.6 T-GDI",
      engine: "1.6L Turbo",
      horsepower: 177,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1899000,
      currency: "TRY",
      country: "TR",
      source: "Kia Türkiye",
    },
  },
  {
    brand: { name: "Kia", country: "Güney Kore" },
    model: { name: "Sportage", startYear: 2025 },
    version: {
      name: "1.6 CRDi",
      engine: "1.6L Dizel",
      horsepower: 136,
      transmission: "Otomatik",
      fuel: "Dizel",
      price: 2099000,
      currency: "TRY",
      country: "TR",
      source: "Kia Türkiye",
    },
  },
  {
    brand: { name: "Kia", country: "Güney Kore" },
    model: { name: "Sorento", startYear: 2025 },
    version: {
      name: "1.6 T-GDI Hybrid",
      engine: "1.6L Hybrid",
      horsepower: 230,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 2899000,
      currency: "TRY",
      country: "TR",
      source: "Kia Türkiye",
    },
  },
  {
    brand: { name: "Kia", country: "Güney Kore" },
    model: { name: "EV6", startYear: 2025 },
    version: {
      name: "2WD",
      engine: "Elektrik",
      horsepower: 229,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 2699000,
      currency: "TRY",
      country: "TR",
      source: "Kia Türkiye",
    },
  },

  // SKODA
  {
    brand: { name: "Skoda", country: "Çekya" },
    model: { name: "Fabia", startYear: 2025 },
    version: {
      name: "1.0 MPI",
      engine: "1.0L",
      horsepower: 80,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 899000,
      currency: "TRY",
      country: "TR",
      source: "Skoda Türkiye",
    },
  },
  {
    brand: { name: "Skoda", country: "Çekya" },
    model: { name: "Scala", startYear: 2025 },
    version: {
      name: "1.0 TSI",
      engine: "1.0L Turbo",
      horsepower: 95,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 1099000,
      currency: "TRY",
      country: "TR",
      source: "Skoda Türkiye",
    },
  },
  {
    brand: { name: "Skoda", country: "Çekya" },
    model: { name: "Scala", startYear: 2025 },
    version: {
      name: "1.5 TSI",
      engine: "1.5L Turbo",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1449000,
      currency: "TRY",
      country: "TR",
      source: "Skoda Türkiye",
    },
  },
  {
    brand: { name: "Skoda", country: "Çekya" },
    model: { name: "Octavia", startYear: 2025 },
    version: {
      name: "1.5 TSI",
      engine: "1.5L Turbo",
      horsepower: 150,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 1499000,
      currency: "TRY",
      country: "TR",
      source: "Skoda Türkiye",
    },
  },
  {
    brand: { name: "Skoda", country: "Çekya" },
    model: { name: "Octavia", startYear: 2025 },
    version: {
      name: "1.5 TSI Style",
      engine: "1.5L Turbo",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1649000,
      currency: "TRY",
      country: "TR",
      source: "Skoda Türkiye",
    },
  },
  {
    brand: { name: "Skoda", country: "Çekya" },
    model: { name: "Octavia", startYear: 2025 },
    version: {
      name: "2.0 TDI Style",
      engine: "2.0L Dizel",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Dizel",
      price: 1899000,
      currency: "TRY",
      country: "TR",
      source: "Skoda Türkiye",
    },
  },
  {
    brand: { name: "Skoda", country: "Çekya" },
    model: { name: "Karoq", startYear: 2025 },
    version: {
      name: "1.5 TSI",
      engine: "1.5L Turbo",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1749000,
      currency: "TRY",
      country: "TR",
      source: "Skoda Türkiye",
    },
  },
  {
    brand: { name: "Skoda", country: "Çekya" },
    model: { name: "Karoq", startYear: 2025 },
    version: {
      name: "2.0 TDI",
      engine: "2.0L Dizel",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Dizel",
      price: 1999000,
      currency: "TRY",
      country: "TR",
      source: "Skoda Türkiye",
    },
  },
  {
    brand: { name: "Skoda", country: "Çekya" },
    model: { name: "Kodiaq", startYear: 2025 },
    version: {
      name: "1.5 TSI",
      engine: "1.5L Turbo",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 2199000,
      currency: "TRY",
      country: "TR",
      source: "Skoda Türkiye",
    },
  },
  {
    brand: { name: "Skoda", country: "Çekya" },
    model: { name: "Superb", startYear: 2025 },
    version: {
      name: "1.5 TSI",
      engine: "1.5L Turbo",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 2299000,
      currency: "TRY",
      country: "TR",
      source: "Skoda Türkiye",
    },
  },

  // OPEL
  {
    brand: { name: "Opel", country: "Almanya" },
    model: { name: "Corsa", startYear: 2025 },
    version: {
      name: "1.2 Edition",
      engine: "1.2L",
      horsepower: 75,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 989000,
      currency: "TRY",
      country: "TR",
      source: "Opel Türkiye",
    },
  },
  {
    brand: { name: "Opel", country: "Almanya" },
    model: { name: "Corsa", startYear: 2025 },
    version: {
      name: "1.2 GS",
      engine: "1.2L Turbo",
      horsepower: 100,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1149000,
      currency: "TRY",
      country: "TR",
      source: "Opel Türkiye",
    },
  },
  {
    brand: { name: "Opel", country: "Almanya" },
    model: { name: "Corsa", startYear: 2025 },
    version: {
      name: "1.2 GS Ultimate",
      engine: "1.2L Turbo",
      horsepower: 130,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1349000,
      currency: "TRY",
      country: "TR",
      source: "Opel Türkiye",
    },
  },
  {
    brand: { name: "Opel", country: "Almanya" },
    model: { name: "Astra", startYear: 2025 },
    version: {
      name: "1.2 GS",
      engine: "1.2L Turbo",
      horsepower: 130,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1349000,
      currency: "TRY",
      country: "TR",
      source: "Opel Türkiye",
    },
  },
  {
    brand: { name: "Opel", country: "Almanya" },
    model: { name: "Astra", startYear: 2025 },
    version: {
      name: "1.5 Diesel",
      engine: "1.5L Dizel",
      horsepower: 130,
      transmission: "Otomatik",
      fuel: "Dizel",
      price: 1599000,
      currency: "TRY",
      country: "TR",
      source: "Opel Türkiye",
    },
  },
  {
    brand: { name: "Opel", country: "Almanya" },
    model: { name: "Astra", startYear: 2025 },
    version: {
      name: "1.6 Plug-in Hybrid",
      engine: "1.6L Hybrid",
      horsepower: 180,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 1899000,
      currency: "TRY",
      country: "TR",
      source: "Opel Türkiye",
    },
  },
  {
    brand: { name: "Opel", country: "Almanya" },
    model: { name: "Mokka", startYear: 2025 },
    version: {
      name: "1.2 GS",
      engine: "1.2L Turbo",
      horsepower: 100,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1249000,
      currency: "TRY",
      country: "TR",
      source: "Opel Türkiye",
    },
  },
  {
    brand: { name: "Opel", country: "Almanya" },
    model: { name: "Grandland", startYear: 2025 },
    version: {
      name: "1.2 GS",
      engine: "1.2L Turbo",
      horsepower: 130,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 1549000,
      currency: "TRY",
      country: "TR",
      source: "Opel Türkiye",
    },
  },
  {
    brand: { name: "Opel", country: "Almanya" },
    model: { name: "Grandland", startYear: 2025 },
    version: {
      name: "1.6 Hybrid",
      engine: "1.6L Hybrid",
      horsepower: 225,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 2199000,
      currency: "TRY",
      country: "TR",
      source: "Opel Türkiye",
    },
  },
  {
    brand: { name: "Opel", country: "Almanya" },
    model: { name: "Combo Life", startYear: 2025 },
    version: {
      name: "1.2",
      engine: "1.2L",
      horsepower: 80,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 1099000,
      currency: "TRY",
      country: "TR",
      source: "Opel Türkiye",
    },
  },

  // TOGG
  {
    brand: { name: "Togg", country: "Türkiye" },
    model: { name: "T10X", startYear: 2025 },
    version: {
      name: "V1 RWD Standart",
      engine: "Elektrik",
      horsepower: 218,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 1505000,
      currency: "TRY",
      country: "TR",
      source: "Togg",
    },
  },
  {
    brand: { name: "Togg", country: "Türkiye" },
    model: { name: "T10X", startYear: 2025 },
    version: {
      name: "V2 RWD",
      engine: "Elektrik",
      horsepower: 218,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 1598000,
      currency: "TRY",
      country: "TR",
      source: "Togg",
    },
  },
  {
    brand: { name: "Togg", country: "Türkiye" },
    model: { name: "T10X", startYear: 2025 },
    version: {
      name: "V2 RWD Long Range",
      engine: "Elektrik",
      horsepower: 320,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 1995000,
      currency: "TRY",
      country: "TR",
      source: "Togg",
    },
  },
  {
    brand: { name: "Togg", country: "Türkiye" },
    model: { name: "T10X", startYear: 2025 },
    version: {
      name: "V1 4x4",
      engine: "Elektrik",
      horsepower: 320,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 2195000,
      currency: "TRY",
      country: "TR",
      source: "Togg",
    },
  },
  {
    brand: { name: "Togg", country: "Türkiye" },
    model: { name: "T10F", startYear: 2025 },
    version: {
      name: "V1 RWD",
      engine: "Elektrik",
      horsepower: 218,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 1878000,
      currency: "TRY",
      country: "TR",
      source: "Togg",
    },
  },
  {
    brand: { name: "Togg", country: "Türkiye" },
    model: { name: "T10F", startYear: 2025 },
    version: {
      name: "V2 RWD",
      engine: "Elektrik",
      horsepower: 320,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 2198000,
      currency: "TRY",
      country: "TR",
      source: "Togg",
    },
  },
  {
    brand: { name: "Togg", country: "Türkiye" },
    model: { name: "T8S", startYear: 2025 },
    version: {
      name: "V1",
      engine: "Elektrik",
      horsepower: 218,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 1655000,
      currency: "TRY",
      country: "TR",
      source: "Togg",
    },
  },
  {
    brand: { name: "Togg", country: "Türkiye" },
    model: { name: "T8S", startYear: 2025 },
    version: {
      name: "V2",
      engine: "Elektrik",
      horsepower: 320,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 1895000,
      currency: "TRY",
      country: "TR",
      source: "Togg",
    },
  },

  // TESLA
  {
    brand: { name: "Tesla", country: "ABD" },
    model: { name: "Model 3", startYear: 2025 },
    version: {
      name: "RWD",
      engine: "Elektrik",
      horsepower: 271,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 2194000,
      currency: "TRY",
      country: "TR",
      source: "Tesla Türkiye",
    },
  },
  {
    brand: { name: "Tesla", country: "ABD" },
    model: { name: "Model 3", startYear: 2025 },
    version: {
      name: "Long Range",
      engine: "Elektrik",
      horsepower: 425,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 2694000,
      currency: "TRY",
      country: "TR",
      source: "Tesla Türkiye",
    },
  },
  {
    brand: { name: "Tesla", country: "ABD" },
    model: { name: "Model 3", startYear: 2025 },
    version: {
      name: "Performance",
      engine: "Elektrik",
      horsepower: 500,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 2994000,
      currency: "TRY",
      country: "TR",
      source: "Tesla Türkiye",
    },
  },
  {
    brand: { name: "Tesla", country: "ABD" },
    model: { name: "Model Y", startYear: 2025 },
    version: {
      name: "RWD",
      engine: "Elektrik",
      horsepower: 245,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 2394000,
      currency: "TRY",
      country: "TR",
      source: "Tesla Türkiye",
    },
  },
  {
    brand: { name: "Tesla", country: "ABD" },
    model: { name: "Model Y", startYear: 2025 },
    version: {
      name: "Long Range",
      engine: "Elektrik",
      horsepower: 384,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 2994000,
      currency: "TRY",
      country: "TR",
      source: "Tesla Türkiye",
    },
  },
  {
    brand: { name: "Tesla", country: "ABD" },
    model: { name: "Model Y", startYear: 2025 },
    version: {
      name: "Performance",
      engine: "Elektrik",
      horsepower: 534,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 3494000,
      currency: "TRY",
      country: "TR",
      source: "Tesla Türkiye",
    },
  },
  {
    brand: { name: "Tesla", country: "ABD" },
    model: { name: "Model S", startYear: 2025 },
    version: {
      name: "Plaid",
      engine: "Elektrik",
      horsepower: 1020,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 6994000,
      currency: "TRY",
      country: "TR",
      source: "Tesla Türkiye",
    },
  },
  {
    brand: { name: "Tesla", country: "ABD" },
    model: { name: "Model X", startYear: 2025 },
    version: {
      name: "Plaid",
      engine: "Elektrik",
      horsepower: 1020,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 7494000,
      currency: "TRY",
      country: "TR",
      source: "Tesla Türkiye",
    },
  },

  // BYD
  {
    brand: { name: "BYD", country: "Çin" },
    model: { name: "Dolphin", startYear: 2025 },
    version: {
      name: "Dynamic",
      engine: "Elektrik",
      horsepower: 177,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 1299000,
      currency: "TRY",
      country: "TR",
      source: "BYD Türkiye",
    },
  },
  {
    brand: { name: "BYD", country: "Çin" },
    model: { name: "Dolphin", startYear: 2025 },
    version: {
      name: "Premium",
      engine: "Elektrik",
      horsepower: 204,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 1499000,
      currency: "TRY",
      country: "TR",
      source: "BYD Türkiye",
    },
  },
  {
    brand: { name: "BYD", country: "Çin" },
    model: { name: "Seal", startYear: 2025 },
    version: {
      name: "Premium",
      engine: "Elektrik",
      horsepower: 313,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 1899000,
      currency: "TRY",
      country: "TR",
      source: "BYD Türkiye",
    },
  },
  {
    brand: { name: "BYD", country: "Çin" },
    model: { name: "Seal", startYear: 2025 },
    version: {
      name: "Performance",
      engine: "Elektrik",
      horsepower: 530,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 2399000,
      currency: "TRY",
      country: "TR",
      source: "BYD Türkiye",
    },
  },
  {
    brand: { name: "BYD", country: "Çin" },
    model: { name: "Seal U", startYear: 2025 },
    version: {
      name: "Comfort",
      engine: "Elektrik",
      horsepower: 218,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 1899000,
      currency: "TRY",
      country: "TR",
      source: "BYD Türkiye",
    },
  },
  {
    brand: { name: "BYD", country: "Çin" },
    model: { name: "Seal U", startYear: 2025 },
    version: {
      name: "Premium",
      engine: "Elektrik",
      horsepower: 313,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 2299000,
      currency: "TRY",
      country: "TR",
      source: "BYD Türkiye",
    },
  },
  {
    brand: { name: "BYD", country: "Çin" },
    model: { name: "Atto 3", startYear: 2025 },
    version: {
      name: "Comfort",
      engine: "Elektrik",
      horsepower: 204,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 1699000,
      currency: "TRY",
      country: "TR",
      source: "BYD Türkiye",
    },
  },
  {
    brand: { name: "BYD", country: "Çin" },
    model: { name: "Atto 3", startYear: 2025 },
    version: {
      name: "Premium",
      engine: "Elektrik",
      horsepower: 262,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 1999000,
      currency: "TRY",
      country: "TR",
      source: "BYD Türkiye",
    },
  },
];

async function importAllPrices() {
  console.log("Tüm marka ve modellerin 2025 fiyatları içe aktarılıyor...\n");

  let savedCount = 0;

  for (const vehicle of allVehiclePrices) {
    try {
      let brandRecord = await prisma.vehicleBrand.findUnique({
        where: { name: vehicle.brand.name },
      });

      if (!brandRecord) {
        brandRecord = await prisma.vehicleBrand.create({
          data: { name: vehicle.brand.name, country: vehicle.brand.country },
        });
      }

      let modelRecord = await prisma.vehicleModel.findFirst({
        where: {
          brandId: brandRecord.id,
          name: { contains: vehicle.model.name },
        },
      });

      if (!modelRecord) {
        modelRecord = await prisma.vehicleModel.create({
          data: {
            brandId: brandRecord.id,
            name: vehicle.model.name,
            startYear: vehicle.model.startYear,
          },
        });
      }

      const existing = await prisma.vehicleVersion.findFirst({
        where: { modelId: modelRecord.id, name: vehicle.version.name },
      });

      if (existing) {
        await prisma.vehicleVersion.update({
          where: { id: existing.id },
          data: {
            price: vehicle.version.price,
            engine: vehicle.version.engine,
            horsepower: vehicle.version.horsepower,
            transmission: vehicle.version.transmission,
            fuel: vehicle.version.fuel,
            source: vehicle.version.source,
          },
        });
      } else {
        await prisma.vehicleVersion.create({
          data: {
            modelId: modelRecord.id,
            name: vehicle.version.name,
            engine: vehicle.version.engine,
            horsepower: vehicle.version.horsepower,
            transmission: vehicle.version.transmission,
            fuel: vehicle.version.fuel,
            price: vehicle.version.price,
            currency: vehicle.version.currency,
            country: vehicle.version.country,
            source: vehicle.version.source,
          },
        });
      }
      savedCount++;
    } catch (e) {
      // Skip errors
    }
  }

  console.log(`✓ ${savedCount} araç fiyatı kaydedildi/güncellendi.`);
}

importAllPrices()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
