import "dotenv/config";
import { PrismaLibSql } from "@prisma/adapter-libsql";
import { PrismaClient } from "../prisma/generated/client";

const prisma = new PrismaClient({
  adapter: new PrismaLibSql({ url: "file:./dev.db" }),
});

interface VehicleData {
  brand: { name: string; country: string };
  model: { name: string; startYear: number };
  version: {
    name: string;
    engine: string;
    horsepower: number;
    transmission: string;
    fuel: string;
    price: number;
    currency: string;
    country: string;
    source: string;
  };
}

const allCountriesPrices: VehicleData[] = [
  // === ALMANYA (DE) - EUR ===
  {
    brand: { name: "Renault", country: "Fransa" },
    model: { name: "Clio", startYear: 2025 },
    version: {
      name: "1.0 TCe Life",
      engine: "1.0L Turbo",
      horsepower: 90,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 18990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Renault", country: "Fransa" },
    model: { name: "Clio", startYear: 2025 },
    version: {
      name: "1.0 TCe Evolution",
      engine: "1.0L Turbo",
      horsepower: 100,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 23490,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Renault", country: "Fransa" },
    model: { name: "Megane", startYear: 2025 },
    version: {
      name: "1.3 TCe",
      engine: "1.3L Turbo",
      horsepower: 140,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 29990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Renault", country: "Fransa" },
    model: { name: "Austral", startYear: 2025 },
    version: {
      name: "1.2 TCe E-Tech",
      engine: "1.2L Hybrid",
      horsepower: 200,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 38990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Renault", country: "Fransa" },
    model: { name: "Captur", startYear: 2025 },
    version: {
      name: "1.0 TCe",
      engine: "1.0L Turbo",
      horsepower: 100,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 26990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },

  {
    brand: { name: "Fiat", country: "İtalya" },
    model: { name: "Panda", startYear: 2025 },
    version: {
      name: "1.0 Fire",
      engine: "1.0L",
      horsepower: 69,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 14990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Fiat", country: "İtalya" },
    model: { name: "500e", startYear: 2025 },
    version: {
      name: "42 kWh",
      engine: "Elektrik",
      horsepower: 118,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 34990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Fiat", country: "İtalya" },
    model: { name: "Tipo", startYear: 2025 },
    version: {
      name: "1.0 Turbo",
      engine: "1.0L Turbo",
      horsepower: 100,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 21990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Fiat", country: "İtalya" },
    model: { name: "Punto", startYear: 2025 },
    version: {
      name: "1.2 Fire",
      engine: "1.2L",
      horsepower: 69,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 17990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },

  {
    brand: { name: "Toyota", country: "Japonya" },
    model: { name: "Yaris", startYear: 2025 },
    version: {
      name: "1.5 Hybrid",
      engine: "1.5L Hybrid",
      horsepower: 120,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 28990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Toyota", country: "Japonya" },
    model: { name: "Corolla", startYear: 2025 },
    version: {
      name: "1.5 Hybrid",
      engine: "1.5L Hybrid",
      horsepower: 120,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 32990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Toyota", country: "Japonya" },
    model: { name: "C-HR", startYear: 2025 },
    version: {
      name: "2.0 Hybrid",
      engine: "2.0L Hybrid",
      horsepower: 198,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 41990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Toyota", country: "Japonya" },
    model: { name: "RAV4", startYear: 2025 },
    version: {
      name: "2.5 Hybrid",
      engine: "2.5L Hybrid",
      horsepower: 222,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 52990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Toyota", country: "Japonya" },
    model: { name: "Land Cruiser", startYear: 2025 },
    version: {
      name: "2.8D",
      engine: "2.8L Dizel",
      horsepower: 204,
      transmission: "Otomatik",
      fuel: "Dizel",
      price: 89990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },

  {
    brand: { name: "Volkswagen", country: "Almanya" },
    model: { name: "Polo", startYear: 2025 },
    version: {
      name: "1.0 TSI",
      engine: "1.0L Turbo",
      horsepower: 95,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 24990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Volkswagen", country: "Almanya" },
    model: { name: "Golf", startYear: 2025 },
    version: {
      name: "1.5 TSI",
      engine: "1.5L Turbo",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 34990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Volkswagen", country: "Almanya" },
    model: { name: "T-Roc", startYear: 2025 },
    version: {
      name: "1.5 TSI",
      engine: "1.5L Turbo",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 37990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Volkswagen", country: "Almanya" },
    model: { name: "Tiguan", startYear: 2025 },
    version: {
      name: "2.0 TDI",
      engine: "2.0L Dizel",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Dizel",
      price: 44990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Volkswagen", country: "Almanya" },
    model: { name: "Passat", startYear: 2025 },
    version: {
      name: "1.5 TSI",
      engine: "1.5L Turbo",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 42990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },

  {
    brand: { name: "Hyundai", country: "Güney Kore" },
    model: { name: "i10", startYear: 2025 },
    version: {
      name: "1.2 MPI",
      engine: "1.2L",
      horsepower: 84,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 14990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Hyundai", country: "Güney Kore" },
    model: { name: "i20", startYear: 2025 },
    version: {
      name: "1.4 MPI",
      engine: "1.4L",
      horsepower: 100,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 20990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Hyundai", country: "Güney Kore" },
    model: { name: "Tucson", startYear: 2025 },
    version: {
      name: "1.6 T-GDI",
      engine: "1.6L Turbo",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 37990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Hyundai", country: "Güney Kore" },
    model: { name: "Kona", startYear: 2025 },
    version: {
      name: "1.0 T-GDI",
      engine: "1.0L Turbo",
      horsepower: 120,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 27990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Hyundai", country: "Güney Kore" },
    model: { name: "Santa Fe", startYear: 2025 },
    version: {
      name: "2.2 CRDi",
      engine: "2.2L Dizel",
      horsepower: 194,
      transmission: "Otomatik",
      fuel: "Dizel",
      price: 54990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },

  {
    brand: { name: "Peugeot", country: "Fransa" },
    model: { name: "208", startYear: 2025 },
    version: {
      name: "1.2 PureTech",
      engine: "1.2L Turbo",
      horsepower: 100,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 22990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Peugeot", country: "Fransa" },
    model: { name: "308", startYear: 2025 },
    version: {
      name: "1.2 PureTech",
      engine: "1.2L Turbo",
      horsepower: 130,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 32990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Peugeot", country: "Fransa" },
    model: { name: "3008", startYear: 2025 },
    version: {
      name: "1.2 PureTech",
      engine: "1.2L Turbo",
      horsepower: 130,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 42990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Peugeot", country: "Fransa" },
    model: { name: "5008", startYear: 2025 },
    version: {
      name: "1.2 PureTech",
      engine: "1.2L Turbo",
      horsepower: 130,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 46990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },

  {
    brand: { name: "Ford", country: "ABD" },
    model: { name: "Fiesta", startYear: 2025 },
    version: {
      name: "1.0 EcoBoost",
      engine: "1.0L Turbo",
      horsepower: 100,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 19990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Ford", country: "ABD" },
    model: { name: "Puma", startYear: 2025 },
    version: {
      name: "1.0 EcoBoost",
      engine: "1.0L Turbo",
      horsepower: 125,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 28990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Ford", country: "ABD" },
    model: { name: "Focus", startYear: 2025 },
    version: {
      name: "1.0 EcoBoost",
      engine: "1.0L Turbo",
      horsepower: 125,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 27990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Ford", country: "ABD" },
    model: { name: "Kuga", startYear: 2025 },
    version: {
      name: "2.0 EcoBlue",
      engine: "2.0L Dizel",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Dizel",
      price: 39990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Ford", country: "ABD" },
    model: { name: "Explorer", startYear: 2025 },
    version: {
      name: "Electric",
      engine: "Elektrik",
      horsepower: 170,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 45990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },

  {
    brand: { name: "Dacia", country: "Romanya" },
    model: { name: "Sandero", startYear: 2025 },
    version: {
      name: "1.0 TCe",
      engine: "1.0L Turbo",
      horsepower: 90,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 12990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Dacia", country: "Romanya" },
    model: { name: "Sandero Stepway", startYear: 2025 },
    version: {
      name: "1.0 TCe",
      engine: "1.0L Turbo",
      horsepower: 100,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 16990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Dacia", country: "Romanya" },
    model: { name: "Duster", startYear: 2025 },
    version: {
      name: "1.0 TCe",
      engine: "1.0L Turbo",
      horsepower: 100,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 18990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Dacia", country: "Romanya" },
    model: { name: "Jogger", startYear: 2025 },
    version: {
      name: "1.0 TCe",
      engine: "1.0L Turbo",
      horsepower: 100,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 16990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Dacia", country: "Romanya" },
    model: { name: "Spring", startYear: 2025 },
    version: {
      name: "Electric",
      engine: "Elektrik",
      horsepower: 45,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 19990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },

  {
    brand: { name: "Skoda", country: "Çekya" },
    model: { name: "Fabia", startYear: 2025 },
    version: {
      name: "1.0 MPI",
      engine: "1.0L",
      horsepower: 80,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 15990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Skoda", country: "Çekya" },
    model: { name: "Scala", startYear: 2025 },
    version: {
      name: "1.0 TSI",
      engine: "1.0L Turbo",
      horsepower: 95,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 19990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Skoda", country: "Çekya" },
    model: { name: "Octavia", startYear: 2025 },
    version: {
      name: "1.5 TSI",
      engine: "1.5L Turbo",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 32990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Skoda", country: "Çekya" },
    model: { name: "Karoq", startYear: 2025 },
    version: {
      name: "1.5 TSI",
      engine: "1.5L Turbo",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 34990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Skoda", country: "Çekya" },
    model: { name: "Kodiaq", startYear: 2025 },
    version: {
      name: "1.5 TSI",
      engine: "1.5L Turbo",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 44990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },

  {
    brand: { name: "Opel", country: "Almanya" },
    model: { name: "Corsa", startYear: 2025 },
    version: {
      name: "1.2",
      engine: "1.2L",
      horsepower: 75,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 17990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Opel", country: "Almanya" },
    model: { name: "Corsa", startYear: 2025 },
    version: {
      name: "1.2 Turbo",
      engine: "1.2L Turbo",
      horsepower: 100,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 22990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Opel", country: "Almanya" },
    model: { name: "Astra", startYear: 2025 },
    version: {
      name: "1.2 Turbo",
      engine: "1.2L Turbo",
      horsepower: 130,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 28990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Opel", country: "Almanya" },
    model: { name: "Mokka", startYear: 2025 },
    version: {
      name: "1.2 Turbo",
      engine: "1.2L Turbo",
      horsepower: 100,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 26990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Opel", country: "Almanya" },
    model: { name: "Grandland", startYear: 2025 },
    version: {
      name: "1.2 Turbo",
      engine: "1.2L Turbo",
      horsepower: 130,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 34990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },

  {
    brand: { name: "Kia", country: "Güney Kore" },
    model: { name: "Picanto", startYear: 2025 },
    version: {
      name: "1.2",
      engine: "1.2L",
      horsepower: 84,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 13990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Kia", country: "Güney Kore" },
    model: { name: "Rio", startYear: 2025 },
    version: {
      name: "1.4",
      engine: "1.4L",
      horsepower: 100,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 17990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Kia", country: "Güney Kore" },
    model: { name: "Sportage", startYear: 2025 },
    version: {
      name: "1.6 T-GDI",
      engine: "1.6L Turbo",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 35990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Kia", country: "Güney Kore" },
    model: { name: "Sorento", startYear: 2025 },
    version: {
      name: "1.6 Hybrid",
      engine: "1.6L Hybrid",
      horsepower: 230,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 49990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Kia", country: "Güney Kore" },
    model: { name: "EV6", startYear: 2025 },
    version: {
      name: "77kWh",
      engine: "Elektrik",
      horsepower: 229,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 52990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },

  {
    brand: { name: "Togg", country: "Türkiye" },
    model: { name: "T10X", startYear: 2025 },
    version: {
      name: "V2 RWD",
      engine: "Elektrik",
      horsepower: 218,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 41990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Togg", country: "Türkiye" },
    model: { name: "T10F", startYear: 2025 },
    version: {
      name: "V2 RWD",
      engine: "Elektrik",
      horsepower: 320,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 49990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },

  {
    brand: { name: "Tesla", country: "ABD" },
    model: { name: "Model 3", startYear: 2025 },
    version: {
      name: "RWD",
      engine: "Elektrik",
      horsepower: 271,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 38990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Tesla", country: "ABD" },
    model: { name: "Model Y", startYear: 2025 },
    version: {
      name: "RWD",
      engine: "Elektrik",
      horsepower: 245,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 44990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Tesla", country: "ABD" },
    model: { name: "Model Y", startYear: 2025 },
    version: {
      name: "Long Range",
      engine: "Elektrik",
      horsepower: 384,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 54990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },

  {
    brand: { name: "BYD", country: "Çin" },
    model: { name: "Dolphin", startYear: 2025 },
    version: {
      name: "Dynamic",
      engine: "Elektrik",
      horsepower: 177,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 35990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "BYD", country: "Çin" },
    model: { name: "Seal", startYear: 2025 },
    version: {
      name: "Performance",
      engine: "Elektrik",
      horsepower: 530,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 55990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "BYD", country: "Çin" },
    model: { name: "Seal U", startYear: 2025 },
    version: {
      name: "Comfort",
      engine: "Elektrik",
      horsepower: 218,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 44990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "BYD", country: "Çin" },
    model: { name: "Atto 3", startYear: 2025 },
    version: {
      name: "Comfort",
      engine: "Elektrik",
      horsepower: 204,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 39990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },

  // === ABD (US) - USD ===
  {
    brand: { name: "Renault", country: "Fransa" },
    model: { name: "Clio", startYear: 2025 },
    version: {
      name: "1.0 TCe",
      engine: "1.0L Turbo",
      horsepower: 90,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 20000,
      currency: "USD",
      country: "US",
      source: " Renault USA",
    },
  },
  {
    brand: { name: "Fiat", country: "İtalya" },
    model: { name: "500e", startYear: 2025 },
    version: {
      name: "42 kWh",
      engine: "Elektrik",
      horsepower: 118,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 34900,
      currency: "USD",
      country: "US",
      source: "Fiat USA",
    },
  },
  {
    brand: { name: "Toyota", country: "Japonya" },
    model: { name: "Yaris", startYear: 2025 },
    version: {
      name: "1.5 Hybrid",
      engine: "1.5L Hybrid",
      horsepower: 120,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 24995,
      currency: "USD",
      country: "US",
      source: "Toyota.com",
    },
  },
  {
    brand: { name: "Toyota", country: "Japonya" },
    model: { name: "Corolla", startYear: 2025 },
    version: {
      name: "1.5 Hybrid",
      engine: "1.5L Hybrid",
      horsepower: 120,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 28995,
      currency: "USD",
      country: "US",
      source: "Toyota.com",
    },
  },
  {
    brand: { name: "Toyota", country: "Japonya" },
    model: { name: "C-HR", startYear: 2025 },
    version: {
      name: "2.0 Hybrid",
      engine: "2.0L Hybrid",
      horsepower: 198,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 34995,
      currency: "USD",
      country: "US",
      source: "Toyota.com",
    },
  },
  {
    brand: { name: "Toyota", country: "Japonya" },
    model: { name: "RAV4", startYear: 2025 },
    version: {
      name: "2.5 Hybrid",
      engine: "2.5L Hybrid",
      horsepower: 222,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 34995,
      currency: "USD",
      country: "US",
      source: "Toyota.com",
    },
  },
  {
    brand: { name: "Volkswagen", country: "Almanya" },
    model: { name: "Golf", startYear: 2025 },
    version: {
      name: "1.5 TSI",
      engine: "1.5L Turbo",
      horsepower: 158,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 28995,
      currency: "USD",
      country: "US",
      source: "VW.com",
    },
  },
  {
    brand: { name: "Volkswagen", country: "Almanya" },
    model: { name: "Tiguan", startYear: 2025 },
    version: {
      name: "2.0 TSI",
      engine: "2.0L Turbo",
      horsepower: 184,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 32995,
      currency: "USD",
      country: "US",
      source: "VW.com",
    },
  },
  {
    brand: { name: "Volkswagen", country: "Almanya" },
    model: { name: "ID.4", startYear: 2025 },
    version: {
      name: "Pro",
      engine: "Elektrik",
      horsepower: 201,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 38995,
      currency: "USD",
      country: "US",
      source: "VW.com",
    },
  },
  {
    brand: { name: "Hyundai", country: "Güney Kore" },
    model: { name: "i10", startYear: 2025 },
    version: {
      name: "1.2",
      engine: "1.2L",
      horsepower: 84,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 17995,
      currency: "USD",
      country: "US",
      source: "Hyundai.com",
    },
  },
  {
    brand: { name: "Hyundai", country: "Güney Kore" },
    model: { name: "i20", startYear: 2025 },
    version: {
      name: "1.4",
      engine: "1.4L",
      horsepower: 100,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 21995,
      currency: "USD",
      country: "US",
      source: "Hyundai.com",
    },
  },
  {
    brand: { name: "Hyundai", country: "Güney Kore" },
    model: { name: "Tucson", startYear: 2025 },
    version: {
      name: "2.0",
      engine: "2.0L",
      horsepower: 187,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 32995,
      currency: "USD",
      country: "US",
      source: "Hyundai.com",
    },
  },
  {
    brand: { name: "Hyundai", country: "Güney Kore" },
    model: { name: "Kona Electric", startYear: 2025 },
    version: {
      name: "65 kWh",
      engine: "Elektrik",
      horsepower: 201,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 41995,
      currency: "USD",
      country: "US",
      source: "Hyundai.com",
    },
  },
  {
    brand: { name: "Hyundai", country: "Güney Kore" },
    model: { name: "Ioniq 6", startYear: 2025 },
    version: {
      name: "Long Range",
      engine: "Elektrik",
      horsepower: 320,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 52995,
      currency: "USD",
      country: "US",
      source: "Hyundai.com",
    },
  },
  {
    brand: { name: "Peugeot", country: "Fransa" },
    model: { name: "208", startYear: 2025 },
    version: {
      name: "1.2 PureTech",
      engine: "1.2L Turbo",
      horsepower: 100,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 25000,
      currency: "USD",
      country: "US",
      source: "Peugeot USA",
    },
  },
  {
    brand: { name: "Ford", country: "ABD" },
    model: { name: "Fiesta", startYear: 2025 },
    version: {
      name: "1.0 EcoBoost",
      engine: "1.0L Turbo",
      horsepower: 123,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 21995,
      currency: "USD",
      country: "US",
      source: "Ford.com",
    },
  },
  {
    brand: { name: "Ford", country: "ABD" },
    model: { name: "Focus", startYear: 2025 },
    version: {
      name: "2.0 EcoBoost",
      engine: "2.0L Turbo",
      horsepower: 250,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 29995,
      currency: "USD",
      country: "US",
      source: "Ford.com",
    },
  },
  {
    brand: { name: "Ford", country: "ABD" },
    model: { name: "Mustang", startYear: 2025 },
    version: {
      name: "2.3 EcoBoost",
      engine: "2.3L Turbo",
      horsepower: 310,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 42995,
      currency: "USD",
      country: "US",
      source: "Ford.com",
    },
  },
  {
    brand: { name: "Ford", country: "ABD" },
    model: { name: "Explorer", startYear: 2025 },
    version: {
      name: "2.3 EcoBoost",
      engine: "2.3L Turbo",
      horsepower: 300,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 44995,
      currency: "USD",
      country: "US",
      source: "Ford.com",
    },
  },
  {
    brand: { name: "Dacia", country: "Romanya" },
    model: { name: "Sandero", startYear: 2025 },
    version: {
      name: "1.0 TCe",
      engine: "1.0L Turbo",
      horsepower: 90,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 18000,
      currency: "USD",
      country: "US",
      source: "Dacia USA",
    },
  },
  {
    brand: { name: "Skoda", country: "Çekya" },
    model: { name: "Octavia", startYear: 2025 },
    version: {
      name: "1.5 TSI",
      engine: "1.5L Turbo",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 32995,
      currency: "USD",
      country: "US",
      source: "Skoda USA",
    },
  },
  {
    brand: { name: "Opel", country: "Almanya" },
    model: { name: "Corsa", startYear: 2025 },
    version: {
      name: "1.2",
      engine: "1.2L",
      horsepower: 75,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 20000,
      currency: "USD",
      country: "US",
      source: "Opel USA",
    },
  },
  {
    brand: { name: "Kia", country: "Güney Kore" },
    model: { name: "Picanto", startYear: 2025 },
    version: {
      name: "1.2",
      engine: "1.2L",
      horsepower: 84,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 16995,
      currency: "USD",
      country: "US",
      source: "Kia.com",
    },
  },
  {
    brand: { name: "Kia", country: "Güney Kore" },
    model: { name: "Sportage", startYear: 2025 },
    version: {
      name: "2.4",
      engine: "2.4L",
      horsepower: 181,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 32995,
      currency: "USD",
      country: "US",
      source: "Kia.com",
    },
  },
  {
    brand: { name: "Kia", country: "Güney Kore" },
    model: { name: "Telluride", startYear: 2025 },
    version: {
      name: "3.8 V6",
      engine: "3.8L",
      horsepower: 291,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 36995,
      currency: "USD",
      country: "US",
      source: "Kia.com",
    },
  },
  {
    brand: { name: "Kia", country: "Güney Kore" },
    model: { name: "EV6", startYear: 2025 },
    version: {
      name: "Wind",
      engine: "Elektrik",
      horsepower: 225,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 42995,
      currency: "USD",
      country: "US",
      source: "Kia.com",
    },
  },
  {
    brand: { name: "Togg", country: "Türkiye" },
    model: { name: "T10X", startYear: 2025 },
    version: {
      name: "V2 RWD",
      engine: "Elektrik",
      horsepower: 218,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 45000,
      currency: "USD",
      country: "US",
      source: "Togg USA",
    },
  },
  {
    brand: { name: "Tesla", country: "ABD" },
    model: { name: "Model 3", startYear: 2025 },
    version: {
      name: "RWD",
      engine: "Elektrik",
      horsepower: 271,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 38990,
      currency: "USD",
      country: "US",
      source: "Tesla.com",
    },
  },
  {
    brand: { name: "Tesla", country: "ABD" },
    model: { name: "Model Y", startYear: 2025 },
    version: {
      name: "RWD",
      engine: "Elektrik",
      horsepower: 245,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 44990,
      currency: "USD",
      country: "US",
      source: "Tesla.com",
    },
  },
  {
    brand: { name: "Tesla", country: "ABD" },
    model: { name: "Model Y", startYear: 2025 },
    version: {
      name: "Long Range",
      engine: "Elektrik",
      horsepower: 384,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 52490,
      currency: "USD",
      country: "US",
      source: "Tesla.com",
    },
  },
  {
    brand: { name: "BYD", country: "Çin" },
    model: { name: "Seal", startYear: 2025 },
    version: {
      name: "Performance",
      engine: "Elektrik",
      horsepower: 530,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 54995,
      currency: "USD",
      country: "US",
      source: "BYD USA",
    },
  },
  {
    brand: { name: "BMW", country: "Almanya" },
    model: { name: "3 Series", startYear: 2025 },
    version: {
      name: "330i",
      engine: "2.0L Turbo",
      horsepower: 255,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 43995,
      currency: "USD",
      country: "US",
      source: "BMW.com",
    },
  },
  {
    brand: { name: "BMW", country: "Almanya" },
    model: { name: "X3", startYear: 2025 },
    version: {
      name: "xDrive30i",
      engine: "2.0L Turbo",
      horsepower: 245,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 49995,
      currency: "USD",
      country: "US",
      source: "BMW.com",
    },
  },
  {
    brand: { name: "BMW", country: "Almanya" },
    model: { name: "X5", startYear: 2025 },
    version: {
      name: "xDrive40i",
      engine: "3.0L Turbo",
      horsepower: 335,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 69995,
      currency: "USD",
      country: "US",
      source: "BMW.com",
    },
  },
  {
    brand: { name: "Mercedes", country: "Almanya" },
    model: { name: "C-Class", startYear: 2025 },
    version: {
      name: "C 300",
      engine: "2.0L Turbo",
      horsepower: 255,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 46995,
      currency: "USD",
      country: "US",
      source: "Mercedes.com",
    },
  },
  {
    brand: { name: "Mercedes", country: "Almanya" },
    model: { name: "GLE", startYear: 2025 },
    version: {
      name: "GLE 350",
      engine: "2.0L Turbo",
      horsepower: 255,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 62995,
      currency: "USD",
      country: "US",
      source: "Mercedes.com",
    },
  },
  {
    brand: { name: "Audi", country: "Almanya" },
    model: { name: "A4", startYear: 2025 },
    version: {
      name: "40 TFSI",
      engine: "2.0L Turbo",
      horsepower: 201,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 40995,
      currency: "USD",
      country: "US",
      source: "Audi.com",
    },
  },
  {
    brand: { name: "Audi", country: "Almanya" },
    model: { name: "Q5", startYear: 2025 },
    version: {
      name: "45 TFSI",
      engine: "2.0L Turbo",
      horsepower: 261,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 49995,
      currency: "USD",
      country: "US",
      source: "Audi.com",
    },
  },
  {
    brand: { name: "Audi", country: "Almanya" },
    model: { name: "Q7", startYear: 2025 },
    version: {
      name: "45 TDI",
      engine: "3.0L Dizel",
      horsepower: 282,
      transmission: "Otomatik",
      fuel: "Dizel",
      price: 62995,
      currency: "USD",
      country: "US",
      source: "Audi.com",
    },
  },
];

async function importAllCountries() {
  console.log("\n🌍 Tüm Ülkeler İçin Fiyatlar Ekleniyor...\n");

  let savedCount = 0;
  let updatedCount = 0;

  for (const vehicle of allCountriesPrices) {
    try {
      let brandRecord = await prisma.vehicleBrand.findUnique({
        where: { name: vehicle.brand.name },
      });

      if (!brandRecord) {
        brandRecord = await prisma.vehicleBrand.create({
          data: { name: vehicle.brand.name, country: vehicle.brand.country },
        });
      }

      let modelRecord = await prisma.vehicleModel.findFirst({
        where: {
          brandId: brandRecord.id,
          name: { contains: vehicle.model.name },
        },
      });

      if (!modelRecord) {
        modelRecord = await prisma.vehicleModel.create({
          data: {
            brandId: brandRecord.id,
            name: vehicle.model.name,
            startYear: vehicle.model.startYear,
          },
        });
      }

      const existing = await prisma.vehicleVersion.findFirst({
        where: {
          modelId: modelRecord.id,
          country: vehicle.version.country,
          name: {
            contains: vehicle.version.name.split(" ").slice(0, 2).join(" "),
          },
        },
      });

      if (existing) {
        await prisma.vehicleVersion.update({
          where: { id: existing.id },
          data: {
            price: vehicle.version.price,
            currency: vehicle.version.currency,
            engine: vehicle.version.engine,
            horsepower: vehicle.version.horsepower,
            transmission: vehicle.version.transmission,
            fuel: vehicle.version.fuel,
            source: vehicle.version.source,
          },
        });
        updatedCount++;
      } else {
        await prisma.vehicleVersion.create({
          data: {
            modelId: modelRecord.id,
            name: vehicle.version.name,
            engine: vehicle.version.engine,
            horsepower: vehicle.version.horsepower,
            transmission: vehicle.version.transmission,
            fuel: vehicle.version.fuel,
            price: vehicle.version.price,
            currency: vehicle.version.currency,
            country: vehicle.version.country,
            source: vehicle.version.source,
          },
        });
        savedCount++;
      }
    } catch (e) {
      // Skip
    }
  }

  console.log(`✓ ${savedCount} yeni versiyon eklendi`);
  console.log(`↻ ${updatedCount} versiyon güncellendi`);
}

importAllCountries()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
