import "dotenv/config";
import { PrismaLibSql } from "@prisma/adapter-libsql";
import { PrismaClient } from "../prisma/generated/client";

const prisma = new PrismaClient({
  adapter: new PrismaLibSql({ url: "file:./dev.db" }),
});

interface OverseasPrice {
  brand: { name: string; country: string };
  model: { name: string; startYear: number };
  version: {
    name: string;
    engine: string;
    horsepower: number;
    transmission: string;
    fuel: string;
    price: number;
    currency: string;
    country: string;
    source: string;
  };
}

const overseasPrices: OverseasPrice[] = [
  // ALMANYA (DE) - Euro cinsinden
  {
    brand: { name: "Renault", country: "Fransa" },
    model: { name: "Clio", startYear: 2025 },
    version: {
      name: "1.0 TCe Life",
      engine: "1.0L Turbo",
      horsepower: 90,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 18990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Renault", country: "Fransa" },
    model: { name: "Clio", startYear: 2025 },
    version: {
      name: "1.0 TCe Evolution",
      engine: "1.0L Turbo",
      horsepower: 100,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 23490,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Renault", country: "Fransa" },
    model: { name: "Megane", startYear: 2025 },
    version: {
      name: "1.3 TCe",
      engine: "1.3L Turbo",
      horsepower: 140,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 29990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Renault", country: "Fransa" },
    model: { name: "Austral", startYear: 2025 },
    version: {
      name: "1.2 TCe E-Tech",
      engine: "1.2L Hybrid",
      horsepower: 200,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 38990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Fiat", country: "İtalya" },
    model: { name: "Panda", startYear: 2025 },
    version: {
      name: "1.0 Fire",
      engine: "1.0L",
      horsepower: 69,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 14990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Fiat", country: "İtalya" },
    model: { name: "500e", startYear: 2025 },
    version: {
      name: "42 kWh",
      engine: "Elektrik",
      horsepower: 118,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 34990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Fiat", country: "İtalya" },
    model: { name: "Tipo", startYear: 2025 },
    version: {
      name: "1.0 Fire",
      engine: "1.0L",
      horsepower: 100,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 21990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Toyota", country: "Japonya" },
    model: { name: "Yaris", startYear: 2025 },
    version: {
      name: "1.5 Hybrid",
      engine: "1.5L Hybrid",
      horsepower: 120,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 28990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Toyota", country: "Japonya" },
    model: { name: "Corolla", startYear: 2025 },
    version: {
      name: "1.5 Hybrid",
      engine: "1.5L Hybrid",
      horsepower: 120,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 32990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Toyota", country: "Japonya" },
    model: { name: "C-HR", startYear: 2025 },
    version: {
      name: "2.0 Hybrid",
      engine: "2.0L Hybrid",
      horsepower: 198,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 41990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Toyota", country: "Japonya" },
    model: { name: "RAV4", startYear: 2025 },
    version: {
      name: "2.5 Hybrid",
      engine: "2.5L Hybrid",
      horsepower: 222,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 52990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Volkswagen", country: "Almanya" },
    model: { name: "Polo", startYear: 2025 },
    version: {
      name: "1.0 TSI",
      engine: "1.0L Turbo",
      horsepower: 95,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 24990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Volkswagen", country: "Almanya" },
    model: { name: "Golf", startYear: 2025 },
    version: {
      name: "1.5 TSI",
      engine: "1.5L Turbo",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 34990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Volkswagen", country: "Almanya" },
    model: { name: "T-Roc", startYear: 2025 },
    version: {
      name: "1.5 TSI",
      engine: "1.5L Turbo",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 37990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Volkswagen", country: "Almanya" },
    model: { name: "Tiguan", startYear: 2025 },
    version: {
      name: "2.0 TDI",
      engine: "2.0L Dizel",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Dizel",
      price: 44990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Hyundai", country: "Güney Kore" },
    model: { name: "i10", startYear: 2025 },
    version: {
      name: "1.2 MPI",
      engine: "1.2L",
      horsepower: 84,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 14990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Hyundai", country: "Güney Kore" },
    model: { name: "i20", startYear: 2025 },
    version: {
      name: "1.4 MPI",
      engine: "1.4L",
      horsepower: 100,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 20990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Hyundai", country: "Güney Kore" },
    model: { name: "Tucson", startYear: 2025 },
    version: {
      name: "1.6 T-GDI",
      engine: "1.6L Turbo",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 37990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Hyundai", country: "Güney Kore" },
    model: { name: "Kona Electric", startYear: 2025 },
    version: {
      name: "65 kWh",
      engine: "Elektrik",
      horsepower: 218,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 42990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Peugeot", country: "Fransa" },
    model: { name: "208", startYear: 2025 },
    version: {
      name: "1.2 PureTech",
      engine: "1.2L Turbo",
      horsepower: 100,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 22990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Peugeot", country: "Fransa" },
    model: { name: "308", startYear: 2025 },
    version: {
      name: "1.2 PureTech",
      engine: "1.2L Turbo",
      horsepower: 130,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 32990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Peugeot", country: "Fransa" },
    model: { name: "3008", startYear: 2025 },
    version: {
      name: "1.2 PureTech",
      engine: "1.2L Turbo",
      horsepower: 130,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 42990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Ford", country: "ABD" },
    model: { name: "Puma", startYear: 2025 },
    version: {
      name: "1.0 EcoBoost",
      engine: "1.0L Turbo",
      horsepower: 125,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 28990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Ford", country: "ABD" },
    model: { name: "Kuga", startYear: 2025 },
    version: {
      name: "2.0 EcoBlue",
      engine: "2.0L Dizel",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Dizel",
      price: 39990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Ford", country: "ABD" },
    model: { name: "Explorer", startYear: 2025 },
    version: {
      name: "Electric",
      engine: "Elektrik",
      horsepower: 170,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 45990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Skoda", country: "Çekya" },
    model: { name: "Octavia", startYear: 2025 },
    version: {
      name: "1.5 TSI",
      engine: "1.5L Turbo",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 32990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Skoda", country: "Çekya" },
    model: { name: "Karoq", startYear: 2025 },
    version: {
      name: "1.5 TSI",
      engine: "1.5L Turbo",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 34990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Opel", country: "Almanya" },
    model: { name: "Corsa", startYear: 2025 },
    version: {
      name: "1.2",
      engine: "1.2L",
      horsepower: 75,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 17990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Opel", country: "Almanya" },
    model: { name: "Astra", startYear: 2025 },
    version: {
      name: "1.2 Turbo",
      engine: "1.2L Turbo",
      horsepower: 130,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 28990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Kia", country: "Güney Kore" },
    model: { name: "Picanto", startYear: 2025 },
    version: {
      name: "1.2",
      engine: "1.2L",
      horsepower: 84,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 13990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Kia", country: "Güney Kore" },
    model: { name: "Sportage", startYear: 2025 },
    version: {
      name: "1.6 T-GDI",
      engine: "1.6L Turbo",
      horsepower: 150,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 35990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },
  {
    brand: { name: "Kia", country: "Güney Kore" },
    model: { name: "EV6", startYear: 2025 },
    version: {
      name: "77.4 kWh",
      engine: "Elektrik",
      horsepower: 229,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 52990,
      currency: "EUR",
      country: "DE",
      source: "Mobile.de",
    },
  },

  // FRANSA (FR) - Euro cinsinden
  {
    brand: { name: "Renault", country: "Fransa" },
    model: { name: "Clio", startYear: 2025 },
    version: {
      name: "1.0 TCe Life",
      engine: "1.0L Turbo",
      horsepower: 90,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 17990,
      currency: "EUR",
      country: "FR",
      source: "LeBonCoin",
    },
  },
  {
    brand: { name: "Renault", country: "Fransa" },
    model: { name: "Megane", startYear: 2025 },
    version: {
      name: "1.3 TCe",
      engine: "1.3L Turbo",
      horsepower: 140,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 28990,
      currency: "EUR",
      country: "FR",
      source: "LeBonCoin",
    },
  },
  {
    brand: { name: "Peugeot", country: "Fransa" },
    model: { name: "208", startYear: 2025 },
    version: {
      name: "1.2 PureTech",
      engine: "1.2L Turbo",
      horsepower: 100,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 21990,
      currency: "EUR",
      country: "FR",
      source: "LeBonCoin",
    },
  },
  {
    brand: { name: "Peugeot", country: "Fransa" },
    model: { name: "3008", startYear: 2025 },
    version: {
      name: "1.2 PureTech",
      engine: "1.2L Turbo",
      horsepower: 130,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 40990,
      currency: "EUR",
      country: "FR",
      source: "LeBonCoin",
    },
  },
  {
    brand: { name: "Citroen", country: "Fransa" },
    model: { name: "C3", startYear: 2025 },
    version: {
      name: "1.2 PureTech",
      engine: "1.2L Turbo",
      horsepower: 100,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 17990,
      currency: "EUR",
      country: "FR",
      source: "LeBonCoin",
    },
  },
  {
    brand: { name: "Citroen", country: "Fransa" },
    model: { name: "C5 X", startYear: 2025 },
    version: {
      name: "1.6 Hybrid",
      engine: "1.6L Hybrid",
      horsepower: 180,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 42990,
      currency: "EUR",
      country: "FR",
      source: "LeBonCoin",
    },
  },

  // İTALYA (IT) - Euro cinsinden
  {
    brand: { name: "Fiat", country: "İtalya" },
    model: { name: "Panda", startYear: 2025 },
    version: {
      name: "1.0 Fire",
      engine: "1.0L",
      horsepower: 69,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 13990,
      currency: "EUR",
      country: "IT",
      source: "Subito.it",
    },
  },
  {
    brand: { name: "Fiat", country: "İtalya" },
    model: { name: "500e", startYear: 2025 },
    version: {
      name: "42 kWh",
      engine: "Elektrik",
      horsepower: 118,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 32990,
      currency: "EUR",
      country: "IT",
      source: "Subito.it",
    },
  },
  {
    brand: { name: "Fiat", country: "İtalya" },
    model: { name: "Tipo", startYear: 2025 },
    version: {
      name: "1.0 Turbo",
      engine: "1.0L Turbo",
      horsepower: 100,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 20990,
      currency: "EUR",
      country: "IT",
      source: "Subito.it",
    },
  },
  {
    brand: { name: "Lancia", country: "İtalya" },
    model: { name: "Ypsilon", startYear: 2025 },
    version: {
      name: "1.0 Hybrid",
      engine: "1.0L Hybrid",
      horsepower: 100,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 24990,
      currency: "EUR",
      country: "IT",
      source: "Subito.it",
    },
  },

  // ABD (US) - Dolar cinsinden
  {
    brand: { name: "Tesla", country: "ABD" },
    model: { name: "Model 3", startYear: 2025 },
    version: {
      name: "RWD",
      engine: "Elektrik",
      horsepower: 271,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 38990,
      currency: "USD",
      country: "US",
      source: "Tesla.com",
    },
  },
  {
    brand: { name: "Tesla", country: "ABD" },
    model: { name: "Model Y", startYear: 2025 },
    version: {
      name: "RWD",
      engine: "Elektrik",
      horsepower: 245,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 44990,
      currency: "USD",
      country: "US",
      source: "Tesla.com",
    },
  },
  {
    brand: { name: "Tesla", country: "ABD" },
    model: { name: "Model Y", startYear: 2025 },
    version: {
      name: "Long Range",
      engine: "Elektrik",
      horsepower: 425,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 52490,
      currency: "USD",
      country: "US",
      source: "Tesla.com",
    },
  },
  {
    brand: { name: "Ford", country: "ABD" },
    model: { name: "F-150", startYear: 2025 },
    version: {
      name: "3.5L V6",
      engine: "3.5L",
      horsepower: 400,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 59995,
      currency: "USD",
      country: "US",
      source: "Ford.com",
    },
  },
  {
    brand: { name: "Ford", country: "ABD" },
    model: { name: "Mustang", startYear: 2025 },
    version: {
      name: "2.3L EcoBoost",
      engine: "2.3L Turbo",
      horsepower: 310,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 42995,
      currency: "USD",
      country: "US",
      source: "Ford.com",
    },
  },
  {
    brand: { name: "Chevrolet", country: "ABD" },
    model: { name: "Corvette", startYear: 2025 },
    version: {
      name: "6.2L V8",
      engine: "6.2L",
      horsepower: 495,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 76500,
      currency: "USD",
      country: "US",
      source: "Chevrolet.com",
    },
  },
  {
    brand: { name: "Toyota", country: "Japonya" },
    model: { name: "Camry", startYear: 2025 },
    version: {
      name: "2.5L Hybrid",
      engine: "2.5L Hybrid",
      horsepower: 225,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 28995,
      currency: "USD",
      country: "US",
      source: "Toyota.com",
    },
  },
  {
    brand: { name: "Toyota", country: "Japonya" },
    model: { name: "RAV4", startYear: 2025 },
    version: {
      name: "2.5L Hybrid",
      engine: "2.5L Hybrid",
      horsepower: 222,
      transmission: "Otomatik",
      fuel: "Hibrit",
      price: 34995,
      currency: "USD",
      country: "US",
      source: "Toyota.com",
    },
  },
  {
    brand: { name: "Honda", country: "Japonya" },
    model: { name: "Civic", startYear: 2025 },
    version: {
      name: "2.0L",
      engine: "2.0L",
      horsepower: 158,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 24995,
      currency: "USD",
      country: "US",
      source: "Honda.com",
    },
  },
  {
    brand: { name: "Hyundai", country: "Güney Kore" },
    model: { name: "Sonata", startYear: 2025 },
    version: {
      name: "2.5L",
      engine: "2.5L",
      horsepower: 191,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 27995,
      currency: "USD",
      country: "US",
      source: "Hyundai.com",
    },
  },
  {
    brand: { name: "Hyundai", country: "Güney Kore" },
    model: { name: "Ioniq 6", startYear: 2025 },
    version: {
      name: "Long Range",
      engine: "Elektrik",
      horsepower: 320,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 52995,
      currency: "USD",
      country: "US",
      source: "Hyundai.com",
    },
  },
  {
    brand: { name: "Kia", country: "Güney Kore" },
    model: { name: "Telluride", startYear: 2025 },
    version: {
      name: "3.8L V6",
      engine: "3.8L",
      horsepower: 291,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 36995,
      currency: "USD",
      country: "US",
      source: "Kia.com",
    },
  },
  {
    brand: { name: "Kia", country: "Güney Kore" },
    model: { name: "EV6", startYear: 2025 },
    version: {
      name: "Wind",
      engine: "Elektrik",
      horsepower: 225,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 42995,
      currency: "USD",
      country: "US",
      source: "Kia.com",
    },
  },
  {
    brand: { name: "BMW", country: "Almanya" },
    model: { name: "3 Series", startYear: 2025 },
    version: {
      name: "330i",
      engine: "2.0L Turbo",
      horsepower: 255,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 43995,
      currency: "USD",
      country: "US",
      source: "BMW.com",
    },
  },
  {
    brand: { name: "BMW", country: "Almanya" },
    model: { name: "X5", startYear: 2025 },
    version: {
      name: "xDrive40i",
      engine: "3.0L Turbo",
      horsepower: 335,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 69995,
      currency: "USD",
      country: "US",
      source: "BMW.com",
    },
  },
  {
    brand: { name: "Mercedes", country: "Almanya" },
    model: { name: "C-Class", startYear: 2025 },
    version: {
      name: "C 300",
      engine: "2.0L Turbo",
      horsepower: 255,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 46995,
      currency: "USD",
      country: "US",
      source: "Mercedes.com",
    },
  },
  {
    brand: { name: "Mercedes", country: "Almanya" },
    model: { name: "GLE", startYear: 2025 },
    version: {
      name: "GLE 350",
      engine: "2.0L Turbo",
      horsepower: 255,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 62995,
      currency: "USD",
      country: "US",
      source: "Mercedes.com",
    },
  },
  {
    brand: { name: "Audi", country: "Almanya" },
    model: { name: "A4", startYear: 2025 },
    version: {
      name: "40 TFSI",
      engine: "2.0L Turbo",
      horsepower: 201,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 40995,
      currency: "USD",
      country: "US",
      source: "Audi.com",
    },
  },
  {
    brand: { name: "Audi", country: "Almanya" },
    model: { name: "Q5", startYear: 2025 },
    version: {
      name: "45 TFSI",
      engine: "2.0L Turbo",
      horsepower: 261,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 49995,
      currency: "USD",
      country: "US",
      source: "Audi.com",
    },
  },
  {
    brand: { name: "Volkswagen", country: "Almanya" },
    model: { name: "Golf", startYear: 2025 },
    version: {
      name: "1.5 TSI",
      engine: "1.5L Turbo",
      horsepower: 158,
      transmission: "Otomatik",
      fuel: "Benzin",
      price: 28995,
      currency: "USD",
      country: "US",
      source: "VW.com",
    },
  },
  {
    brand: { name: "Volkswagen", country: "Almanya" },
    model: { name: "ID.4", startYear: 2025 },
    version: {
      name: "Pro",
      engine: "Elektrik",
      horsepower: 201,
      transmission: "Otomatik",
      fuel: "Elektrik",
      price: 38995,
      currency: "USD",
      country: "US",
      source: "VW.com",
    },
  },
  {
    brand: { name: "Dacia", country: "Romanya" },
    model: { name: "Sandero", startYear: 2025 },
    version: {
      name: "1.0 TCe",
      engine: "1.0L Turbo",
      horsepower: 90,
      transmission: "Manuel",
      fuel: "Benzin",
      price: 15990,
      currency: "EUR",
      country: "FR",
      source: "LeBonCoin",
    },
  },
];

async function importOverseasPrices() {
  console.log("\n🌍 Yurt Dışı Fiyatları İçe Aktarılıyor...\n");

  let savedCount = 0;
  let updatedCount = 0;

  for (const vehicle of overseasPrices) {
    try {
      let brandRecord = await prisma.vehicleBrand.findUnique({
        where: { name: vehicle.brand.name },
      });

      if (!brandRecord) {
        brandRecord = await prisma.vehicleBrand.create({
          data: { name: vehicle.brand.name, country: vehicle.brand.country },
        });
      }

      let modelRecord = await prisma.vehicleModel.findFirst({
        where: {
          brandId: brandRecord.id,
          name: { contains: vehicle.model.name },
        },
      });

      if (!modelRecord) {
        modelRecord = await prisma.vehicleModel.create({
          data: {
            brandId: brandRecord.id,
            name: vehicle.model.name,
            startYear: vehicle.model.startYear,
          },
        });
      }

      const existing = await prisma.vehicleVersion.findFirst({
        where: {
          modelId: modelRecord.id,
          country: vehicle.version.country,
        },
      });

      if (existing) {
        await prisma.vehicleVersion.update({
          where: { id: existing.id },
          data: {
            price: vehicle.version.price,
            currency: vehicle.version.currency,
            engine: vehicle.version.engine,
            horsepower: vehicle.version.horsepower,
            transmission: vehicle.version.transmission,
            fuel: vehicle.version.fuel,
            source: vehicle.version.source,
          },
        });
        updatedCount++;
      } else {
        await prisma.vehicleVersion.create({
          data: {
            modelId: modelRecord.id,
            name: vehicle.version.name,
            engine: vehicle.version.engine,
            horsepower: vehicle.version.horsepower,
            transmission: vehicle.version.transmission,
            fuel: vehicle.version.fuel,
            price: vehicle.version.price,
            currency: vehicle.version.currency,
            country: vehicle.version.country,
            source: vehicle.version.source,
          },
        });
        savedCount++;
      }
    } catch (e) {
      // Skip errors
    }
  }

  console.log(`✓ ${savedCount} yeni versiyon eklendi`);
  console.log(`↻ ${updatedCount} versiyon güncellendi`);
}

importOverseasPrices()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
