import "dotenv/config";
import { PrismaLibSql } from "@prisma/adapter-libsql";
import { PrismaClient } from "../prisma/generated/client";

const prisma = new PrismaClient({
  adapter: new PrismaLibSql({ url: "file:./dev.db" }),
});

const missingVehicles = [
  // AUDI - A3 ve diğerleri (USD -> TL çevrilmiş)
  {
    brand: "Audi",
    model: "A3",
    version: "35 TFSI",
    engine: "1.5L Turbo",
    hp: 150,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1850000,
    country: "TR",
    source: "Audi Türkiye",
  },
  {
    brand: "Audi",
    model: "A3",
    version: "40 TFSI",
    engine: "2.0L Turbo",
    hp: 190,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 2150000,
    country: "TR",
    source: "Audi Türkiye",
  },
  {
    brand: "Audi",
    model: "A3",
    version: "45 TFSI e",
    engine: "1.5L Hybrid",
    hp: 204,
    trans: "Otomatik",
    fuel: "Hibrit",
    price: 2650000,
    country: "TR",
    source: "Audi Türkiye",
  },
  {
    brand: "Audi",
    model: "A4",
    version: "40 TFSI",
    engine: "2.0L Turbo",
    hp: 190,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 2550000,
    country: "TR",
    source: "Audi Türkiye",
  },
  {
    brand: "Audi",
    model: "A4",
    version: "45 TDI",
    engine: "3.0L Dizel",
    hp: 204,
    trans: "Otomatik",
    fuel: "Dizel",
    price: 3200000,
    country: "TR",
    source: "Audi Türkiye",
  },
  {
    brand: "Audi",
    model: "Q3",
    version: "35 TFSI",
    engine: "1.5L Turbo",
    hp: 150,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 2450000,
    country: "TR",
    source: "Audi Türkiye",
  },
  {
    brand: "Audi",
    model: "Q3",
    version: "40 TFSI",
    engine: "2.0L Turbo",
    hp: 180,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 2850000,
    country: "TR",
    source: "Audi Türkiye",
  },
  {
    brand: "Audi",
    model: "Q5",
    version: "40 TDI",
    engine: "2.0L Dizel",
    hp: 204,
    trans: "Otomatik",
    fuel: "Dizel",
    price: 3850000,
    country: "TR",
    source: "Audi Türkiye",
  },
  {
    brand: "Audi",
    model: "Q5",
    version: "45 TFSI",
    engine: "2.0L Turbo",
    hp: 265,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 3650000,
    country: "TR",
    source: "Audi Türkiye",
  },
  {
    brand: "Audi",
    model: "Q7",
    version: "45 TDI",
    engine: "3.0L Dizel",
    hp: 231,
    trans: "Otomatik",
    fuel: "Dizel",
    price: 5500000,
    country: "TR",
    source: "Audi Türkiye",
  },
  {
    brand: "Audi",
    model: "Q8",
    version: "55 TFSI",
    engine: "3.0L Turbo",
    hp: 340,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 7500000,
    country: "TR",
    source: "Audi Türkiye",
  },
  {
    brand: "Audi",
    model: "e-tron",
    version: "55 Quattro",
    engine: "Elektrik",
    hp: 408,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 5500000,
    country: "TR",
    source: "Audi Türkiye",
  },

  // BMW - Eksik modeller
  {
    brand: "BMW",
    model: "1 Serisi",
    version: "118i",
    engine: "1.5L Turbo",
    hp: 136,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1650000,
    country: "TR",
    source: "BMW Türkiye",
  },
  {
    brand: "BMW",
    model: "1 Serisi",
    version: "120i",
    engine: "2.0L Turbo",
    hp: 178,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1950000,
    country: "TR",
    source: "BMW Türkiye",
  },
  {
    brand: "BMW",
    model: "2 Serisi Gran Coupe",
    version: "218i",
    engine: "1.5L Turbo",
    hp: 140,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1850000,
    country: "TR",
    source: "BMW Türkiye",
  },
  {
    brand: "BMW",
    model: "3 Serisi",
    version: "320i",
    engine: "2.0L Turbo",
    hp: 156,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 2450000,
    country: "TR",
    source: "BMW Türkiye",
  },
  {
    brand: "BMW",
    model: "3 Serisi",
    version: "330i",
    engine: "2.0L Turbo",
    hp: 245,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 2950000,
    country: "TR",
    source: "BMW Türkiye",
  },
  {
    brand: "BMW",
    model: "5 Serisi",
    version: "520i",
    engine: "2.0L Turbo",
    hp: 184,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 3450000,
    country: "TR",
    source: "BMW Türkiye",
  },
  {
    brand: "BMW",
    model: "5 Serisi",
    version: "530i",
    engine: "2.0L Turbo",
    hp: 252,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 4050000,
    country: "TR",
    source: "BMW Türkiye",
  },
  {
    brand: "BMW",
    model: "X1",
    version: "sDrive18i",
    engine: "1.5L Turbo",
    hp: 136,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 2150000,
    country: "TR",
    source: "BMW Türkiye",
  },
  {
    brand: "BMW",
    model: "X3",
    version: "xDrive20i",
    engine: "2.0L Turbo",
    hp: 184,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 3350000,
    country: "TR",
    source: "BMW Türkiye",
  },
  {
    brand: "BMW",
    model: "X5",
    version: "xDrive30d",
    engine: "3.0L Dizel",
    hp: 286,
    trans: "Otomatik",
    fuel: "Dizel",
    price: 4950000,
    country: "TR",
    source: "BMW Türkiye",
  },
  {
    brand: "BMW",
    model: "i4",
    version: "eDrive35",
    engine: "Elektrik",
    hp: 286,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 2950000,
    country: "TR",
    source: "BMW Türkiye",
  },
  {
    brand: "BMW",
    model: "iX",
    version: "xDrive40",
    engine: "Elektrik",
    hp: 326,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 5500000,
    country: "TR",
    source: "BMW Türkiye",
  },

  // MERCEDES - Eksik modeller
  {
    brand: "Mercedes",
    model: "A Serisi",
    version: "A 180",
    engine: "1.3L Turbo",
    hp: 136,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1750000,
    country: "TR",
    source: "Mercedes Türkiye",
  },
  {
    brand: "Mercedes",
    model: "A Serisi",
    version: "A 200",
    engine: "1.3L Turbo",
    hp: 163,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 2050000,
    country: "TR",
    source: "Mercedes Türkiye",
  },
  {
    brand: "Mercedes",
    model: "C Serisi",
    version: "C 180",
    engine: "1.5L Turbo",
    hp: 170,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 2650000,
    country: "TR",
    source: "Mercedes Türkiye",
  },
  {
    brand: "Mercedes",
    model: "C Serisi",
    version: "C 300",
    engine: "2.0L Turbo",
    hp: 258,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 3450000,
    country: "TR",
    source: "Mercedes Türkiye",
  },
  {
    brand: "Mercedes",
    model: "E Serisi",
    version: "E 200",
    engine: "2.0L Turbo",
    hp: 197,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 3850000,
    country: "TR",
    source: "Mercedes Türkiye",
  },
  {
    brand: "Mercedes",
    model: "GLA",
    version: "GLA 180",
    engine: "1.3L Turbo",
    hp: 136,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 2350000,
    country: "TR",
    source: "Mercedes Türkiye",
  },
  {
    brand: "Mercedes",
    model: "GLC",
    version: "GLC 200",
    engine: "2.0L Turbo",
    hp: 197,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 3850000,
    country: "TR",
    source: "Mercedes Türkiye",
  },
  {
    brand: "Mercedes",
    model: "GLE",
    version: "GLE 300",
    engine: "2.0L Turbo",
    hp: 269,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 4950000,
    country: "TR",
    source: "Mercedes Türkiye",
  },
  {
    brand: "Mercedes",
    model: "EQE",
    version: "350+",
    engine: "Elektrik",
    hp: 292,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 5500000,
    country: "TR",
    source: "Mercedes Türkiye",
  },
  {
    brand: "Mercedes",
    model: "EQS",
    version: "580 4MATIC",
    engine: "Elektrik",
    hp: 516,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 8500000,
    country: "TR",
    source: "Mercedes Türkiye",
  },

  // VOLKSWAGEN - Eksik modeller
  {
    brand: "Volkswagen",
    model: "Passat",
    version: "1.5 TSI",
    engine: "1.5L Turbo",
    hp: 150,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1990000,
    country: "TR",
    source: "VW Türkiye",
  },
  {
    brand: "Volkswagen",
    model: "Arteon",
    version: "2.0 TSI",
    engine: "2.0L Turbo",
    hp: 190,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 2750000,
    country: "TR",
    source: "VW Türkiye",
  },
  {
    brand: "Volkswagen",
    model: "Touareg",
    version: "3.0 V6 TDI",
    engine: "3.0L Dizel",
    hp: 286,
    trans: "Otomatik",
    fuel: "Dizel",
    price: 4500000,
    country: "TR",
    source: "VW Türkiye",
  },
  {
    brand: "Volkswagen",
    model: "ID.3",
    version: "Pro",
    engine: "Elektrik",
    hp: 204,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 1790000,
    country: "TR",
    source: "VW Türkiye",
  },
  {
    brand: "Volkswagen",
    model: "ID.5",
    version: "Pro",
    engine: "Elektrik",
    hp: 204,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 2590000,
    country: "TR",
    source: "VW Türkiye",
  },

  // TOYOTA - Eksik modeller
  {
    brand: "Toyota",
    model: "Supra",
    version: "2.0T",
    engine: "2.0L Turbo",
    hp: 258,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 4500000,
    country: "TR",
    source: "Toyota Türkiye",
  },
  {
    brand: "Toyota",
    model: "Prius",
    version: "1.8 Hybrid",
    engine: "1.8L Hybrid",
    hp: 122,
    trans: "Otomatik",
    fuel: "Hibrit",
    price: 1490000,
    country: "TR",
    source: "Toyota Türkiye",
  },

  // SKODA - Eksik modeller
  {
    brand: "Skoda",
    model: "Enyaq",
    version: "60",
    engine: "Elektrik",
    hp: 180,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 1950000,
    country: "TR",
    source: "Skoda Türkiye",
  },
  {
    brand: "Skoda",
    model: "Enyaq",
    version: "80x",
    engine: "Elektrik",
    hp: 265,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 2650000,
    country: "TR",
    source: "Skoda Türkiye",
  },

  // PEUGEOT - Eksik modeller
  {
    brand: "Peugeot",
    model: "508",
    version: "1.6 Hybrid",
    engine: "1.6L Hybrid",
    hp: 225,
    trans: "Otomatik",
    fuel: "Hibrit",
    price: 2290000,
    country: "TR",
    source: "Peugeot Türkiye",
  },

  // KIA - Eksik modeller
  {
    brand: "Kia",
    model: "Niro",
    version: "1.6 Hybrid",
    engine: "1.6L Hybrid",
    hp: 139,
    trans: "Otomatik",
    fuel: "Hibrit",
    price: 1390000,
    country: "TR",
    source: "Kia Türkiye",
  },
  {
    brand: "Kia",
    model: "Niro EV",
    engine: "Elektrik",
    hp: 204,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 1590000,
    country: "TR",
    source: "Kia Türkiye",
  },

  // HYUNDAI - Eksik modeller
  {
    brand: "Hyundai",
    model: "Ioniq 5",
    version: "58 kWh",
    engine: "Elektrik",
    hp: 170,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 1890000,
    country: "TR",
    source: "Hyundai Türkiye",
  },
  {
    brand: "Hyundai",
    model: "Ioniq 6",
    version: "77 kWh",
    engine: "Elektrik",
    hp: 229,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 2290000,
    country: "TR",
    source: "Hyundai Türkiye",
  },

  // OPEL - Eksik modeller
  {
    brand: "Opel",
    model: "Zafira Life",
    version: "2.0 CDTi",
    engine: "2.0L Dizel",
    hp: 177,
    trans: "Otomatik",
    fuel: "Dizel",
    price: 2290000,
    country: "TR",
    source: "Opel Türkiye",
  },

  // RENAULT - Eksik modeller
  {
    brand: "Renault",
    model: "Espace",
    version: "1.2 E-Tech",
    engine: "1.2L Hybrid",
    hp: 200,
    trans: "Otomatik",
    fuel: "Hibrit",
    price: 2490000,
    country: "TR",
    source: "Renault Türkiye",
  },
  {
    brand: "Renault",
    model: "Rafale",
    version: "1.2 E-Tech",
    engine: "1.2L Hybrid",
    hp: 300,
    trans: "Otomatik",
    fuel: "Hibrit",
    price: 2790000,
    country: "TR",
    source: "Renault Türkiye",
  },

  // CITROEN - Eksik modeller
  {
    brand: "Citroen",
    model: "C5 X",
    version: "1.6 Hybrid",
    engine: "1.6L Hybrid",
    hp: 180,
    trans: "Otomatik",
    fuel: "Hibrit",
    price: 1790000,
    country: "TR",
    source: "Citroen Türkiye",
  },

  // TESLA - Eksik modeller
  {
    brand: "Tesla",
    model: "Model S",
    version: "Plaid",
    engine: "Elektrik",
    hp: 1020,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 8500000,
    country: "TR",
    source: "Tesla Türkiye",
  },
  {
    brand: "Tesla",
    model: "Model X",
    version: "Plaid",
    engine: "Elektrik",
    hp: 1020,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 9500000,
    country: "TR",
    source: "Tesla Türkiye",
  },

  // TOGG - Eksik modeller
  {
    brand: "Togg",
    model: "T10X",
    version: "V2 4x4",
    engine: "Elektrik",
    hp: 320,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 2195000,
    country: "TR",
    source: "Togg",
  },
  {
    brand: "Togg",
    model: "T10F",
    version: "V2 Long Range",
    engine: "Elektrik",
    hp: 320,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 2495000,
    country: "TR",
    source: "Togg",
  },

  // BYD - Eksik modeller
  {
    brand: "BYD",
    model: "Seal U",
    version: "Premium",
    engine: "Elektrik",
    hp: 313,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 2290000,
    country: "TR",
    source: "BYD Türkiye",
  },

  // DACIA - Eksik modeller
  {
    brand: "Dacia",
    model: "Duster",
    version: "1.5 Blue dCi",
    engine: "1.5L Dizel",
    hp: 115,
    trans: "Manuel",
    fuel: "Dizel",
    price: 1349000,
    country: "TR",
    source: "Dacia Türkiye",
  },
];

async function updateMissing() {
  console.log("\n🔄 EKSIK MODELLER EKLENİYOR...\n");

  let added = 0;

  for (const v of missingVehicles) {
    try {
      let brand = await prisma.vehicleBrand.findUnique({
        where: { name: v.brand },
      });
      if (!brand) {
        brand = await prisma.vehicleBrand.create({
          data: {
            name: v.brand,
            country:
              v.brand === "Mercedes" ||
              v.brand === "BMW" ||
              v.brand === "Audi" ||
              v.brand === "Volkswagen"
                ? "Almanya"
                : "Diğer",
          },
        });
      }

      let model = await prisma.vehicleModel.findFirst({
        where: { brandId: brand.id, name: v.model },
      });
      if (!model) {
        model = await prisma.vehicleModel.create({
          data: { brandId: brand.id, name: v.model, startYear: 2025 },
        });
      }

      const existing = await prisma.vehicleVersion.findFirst({
        where: { modelId: model.id, name: v.version },
      });
      if (!existing) {
        await prisma.vehicleVersion.create({
          data: {
            modelId: model.id,
            name: v.version,
            engine: v.engine,
            horsepower: v.hp,
            transmission: v.trans,
            fuel: v.fuel,
            price: v.price,
            currency: "TL",
            country: v.country,
            source: v.source,
          },
        });
        added++;
        console.log(`  + ${v.brand} ${v.model} ${v.version}`);
      }
    } catch (e) {
      // Skip
    }
  }

  console.log(`\n✓ ${added} yeni versiyon eklendi`);
}

updateMissing().finally(() => prisma.$disconnect());
