import "dotenv/config";
import { PrismaLibSql } from "@prisma/adapter-libsql";
import { PrismaClient } from "../prisma/generated/client";

const prisma = new PrismaClient({
  adapter: new PrismaLibSql({ url: "file:./dev.db" }),
});

const currentPrices2025 = [
  // FIAT
  {
    brand: "Fiat",
    model: "Topolino",
    version: "6 kW/8 HP",
    engine: "Elektrik",
    hp: 8,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 605900,
  },
  {
    brand: "Fiat",
    model: "Panda",
    version: "1.0 Fire",
    engine: "1.0L",
    hp: 69,
    trans: "Manuel",
    fuel: "Benzin",
    price: 699000,
  },
  {
    brand: "Fiat",
    model: "Egea Sedan",
    version: "1.4 Fire Easy",
    engine: "1.4L",
    hp: 95,
    trans: "Manuel",
    fuel: "Benzin",
    price: 1184900,
  },
  {
    brand: "Fiat",
    model: "Egea Sedan",
    version: "1.4 Fire Lounge",
    engine: "1.4L",
    hp: 95,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1349000,
  },
  {
    brand: "Fiat",
    model: "Egea Cross",
    version: "1.4 Fire Street",
    engine: "1.4L",
    hp: 95,
    trans: "Manuel",
    fuel: "Benzin",
    price: 1270520,
  },
  {
    brand: "Fiat",
    model: "Egea Cross",
    version: "1.4 Fire Lounge",
    engine: "1.4L",
    hp: 95,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1449000,
  },
  {
    brand: "Fiat",
    model: "Grande Panda",
    version: "1.2 Hybrid",
    engine: "1.2L Hybrid",
    hp: 100,
    trans: "Otomatik",
    fuel: "Hibrit",
    price: 1449900,
  },
  {
    brand: "Fiat",
    model: "Doblo",
    version: "1.2 Easy",
    engine: "1.2L",
    hp: 80,
    trans: "Manuel",
    fuel: "Benzin",
    price: 1159000,
  },
  {
    brand: "Fiat",
    model: "Doblo",
    version: "1.6 Multijet",
    engine: "1.6L Dizel",
    hp: 120,
    trans: "Manuel",
    fuel: "Dizel",
    price: 1399000,
  },
  {
    brand: "Fiat",
    model: "500e",
    version: "42 kWh",
    engine: "Elektrik",
    hp: 118,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 1299000,
  },

  // DACIA
  {
    brand: "Dacia",
    model: "Sandero",
    version: "1.0 TCe Essential",
    engine: "1.0L Turbo",
    hp: 90,
    trans: "Manuel",
    fuel: "Benzin",
    price: 749000,
  },
  {
    brand: "Dacia",
    model: "Sandero",
    version: "1.0 TCe Expression",
    engine: "1.0L Turbo",
    hp: 90,
    trans: "Manuel",
    fuel: "Benzin",
    price: 899000,
  },
  {
    brand: "Dacia",
    model: "Sandero Stepway",
    version: "1.0 TCe Expression",
    engine: "1.0L Turbo",
    hp: 90,
    trans: "Manuel",
    fuel: "Benzin",
    price: 999000,
  },
  {
    brand: "Dacia",
    model: "Sandero Stepway",
    version: "1.0 TCe Extreme",
    engine: "1.0L Turbo",
    hp: 100,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1313000,
  },
  {
    brand: "Dacia",
    model: "Jogger",
    version: "1.0 TCe Essential",
    engine: "1.0L Turbo",
    hp: 100,
    trans: "Manuel",
    fuel: "Benzin",
    price: 999000,
  },
  {
    brand: "Dacia",
    model: "Jogger",
    version: "1.0 TCe Extreme Eco-G",
    engine: "1.0L Turbo",
    hp: 100,
    trans: "Manuel",
    fuel: "Benzin/LPG",
    price: 1492000,
  },
  {
    brand: "Dacia",
    model: "Duster",
    version: "1.0 TCe 4x2",
    engine: "1.0L Turbo",
    hp: 100,
    trans: "Manuel",
    fuel: "Benzin",
    price: 1199000,
  },
  {
    brand: "Dacia",
    model: "Duster",
    version: "1.0 TCe 4x4",
    engine: "1.0L Turbo",
    hp: 125,
    trans: "Manuel",
    fuel: "Benzin",
    price: 1645000,
  },
  {
    brand: "Dacia",
    model: "Duster",
    version: "1.5 Blue dCi",
    engine: "1.5L Dizel",
    hp: 115,
    trans: "Manuel",
    fuel: "Dizel",
    price: 1349000,
  },
  {
    brand: "Dacia",
    model: "Spring",
    version: "Electric",
    engine: "Elektrik",
    hp: 45,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 799000,
  },

  // RENAULT
  {
    brand: "Renault",
    model: "Clio",
    version: "1.0 SCE Life",
    engine: "1.0L",
    hp: 65,
    trans: "Manuel",
    fuel: "Benzin",
    price: 899000,
  },
  {
    brand: "Renault",
    model: "Clio",
    version: "1.0 TCE Joy",
    engine: "1.0L Turbo",
    hp: 90,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1179000,
  },
  {
    brand: "Renault",
    model: "Clio",
    version: "1.0 TCE Evolution",
    engine: "1.0L Turbo",
    hp: 100,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1349000,
  },
  {
    brand: "Renault",
    model: "Megane",
    version: "1.3 TCE Joy",
    engine: "1.3L Turbo",
    hp: 130,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1399000,
  },
  {
    brand: "Renault",
    model: "Megane",
    version: "1.3 TCE Evolution",
    engine: "1.3L Turbo",
    hp: 150,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1599000,
  },
  {
    brand: "Renault",
    model: "Austral",
    version: "1.2 TCE Mild Hybrid",
    engine: "1.2L Hybrid",
    hp: 140,
    trans: "Otomatik",
    fuel: "Hibrit",
    price: 1899000,
  },
  {
    brand: "Renault",
    model: "Austral",
    version: "1.2 TCE E-Tech",
    engine: "1.2L Hybrid",
    hp: 200,
    trans: "Otomatik",
    fuel: "Hibrit",
    price: 2299000,
  },
  {
    brand: "Renault",
    model: "Symbioz",
    version: "1.2 TCE E-Tech",
    engine: "1.2L Hybrid",
    hp: 140,
    trans: "Otomatik",
    fuel: "Hibrit",
    price: 1699000,
  },
  {
    brand: "Renault",
    model: "Captur",
    version: "1.0 TCE Joy",
    engine: "1.0L Turbo",
    hp: 90,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1299000,
  },
  {
    brand: "Renault",
    model: "Arkana",
    version: "1.3 TCE E-Tech",
    engine: "1.3L Hybrid",
    hp: 140,
    trans: "Otomatik",
    fuel: "Hibrit",
    price: 1899000,
  },

  // TOYOTA
  {
    brand: "Toyota",
    model: "Yaris",
    version: "1.5 Hybrid",
    engine: "1.5L Hybrid",
    hp: 120,
    trans: "Otomatik",
    fuel: "Hibrit",
    price: 1349000,
  },
  {
    brand: "Toyota",
    model: "Yaris",
    version: "1.5 Hybrid GR Sport",
    engine: "1.5L Hybrid",
    hp: 130,
    trans: "Otomatik",
    fuel: "Hibrit",
    price: 1599000,
  },
  {
    brand: "Toyota",
    model: "Corolla",
    version: "1.5 Hybrid Dream",
    engine: "1.5L Hybrid",
    hp: 120,
    trans: "Otomatik",
    fuel: "Hibrit",
    price: 1549000,
  },
  {
    brand: "Toyota",
    model: "Corolla",
    version: "1.5 Hybrid GR Sport",
    engine: "1.5L Hybrid",
    hp: 130,
    trans: "Otomatik",
    fuel: "Hibrit",
    price: 1749000,
  },
  {
    brand: "Toyota",
    model: "Corolla",
    version: "2.0 Hybrid Adventure",
    engine: "2.0L Hybrid",
    hp: 180,
    trans: "Otomatik",
    fuel: "Hibrit",
    price: 1999000,
  },
  {
    brand: "Toyota",
    model: "C-HR",
    version: "1.8 Hybrid Dream",
    engine: "1.8L Hybrid",
    hp: 140,
    trans: "Otomatik",
    fuel: "Hibrit",
    price: 1699000,
  },
  {
    brand: "Toyota",
    model: "C-HR",
    version: "2.0 Hybrid GR Sport",
    engine: "2.0L Hybrid",
    hp: 180,
    trans: "Otomatik",
    fuel: "Hibrit",
    price: 2199000,
  },
  {
    brand: "Toyota",
    model: "RAV4",
    version: "2.0 Hybrid Adventure",
    engine: "2.0L Hybrid",
    hp: 180,
    trans: "Otomatik",
    fuel: "Hibrit",
    price: 2699000,
  },
  {
    brand: "Toyota",
    model: "RAV4",
    version: "2.5 Hybrid Luxury",
    engine: "2.5L Hybrid",
    hp: 220,
    trans: "Otomatik",
    fuel: "Hibrit",
    price: 3299000,
  },
  {
    brand: "Toyota",
    model: "Supra",
    version: "2.0T",
    engine: "2.0L Turbo",
    hp: 258,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 4500000,
  },

  // VOLKSWAGEN
  {
    brand: "Volkswagen",
    model: "Polo",
    version: "1.0 TSI Life",
    engine: "1.0L Turbo",
    hp: 95,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1299000,
  },
  {
    brand: "Volkswagen",
    model: "Polo",
    version: "1.0 TSI Style",
    engine: "1.0L Turbo",
    hp: 110,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1499000,
  },
  {
    brand: "Volkswagen",
    model: "Golf",
    version: "1.5 TSI Life",
    engine: "1.5L Turbo",
    hp: 130,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1549000,
  },
  {
    brand: "Volkswagen",
    model: "Golf",
    version: "1.5 TSI Style",
    engine: "1.5L Turbo",
    hp: 150,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1799000,
  },
  {
    brand: "Volkswagen",
    model: "Golf",
    version: "2.0 TDI Style",
    engine: "2.0L Dizel",
    hp: 150,
    trans: "Otomatik",
    fuel: "Dizel",
    price: 1999000,
  },
  {
    brand: "Volkswagen",
    model: "T-Roc",
    version: "1.5 TSI Life",
    engine: "1.5L Turbo",
    hp: 150,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1799000,
  },
  {
    brand: "Volkswagen",
    model: "T-Roc",
    version: "2.0 TSI 4Motion",
    engine: "2.0L Turbo",
    hp: 190,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 2299000,
  },
  {
    brand: "Volkswagen",
    model: "Tiguan",
    version: "1.5 TSI Life",
    engine: "1.5L Turbo",
    hp: 150,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 2099000,
  },
  {
    brand: "Volkswagen",
    model: "Tiguan",
    version: "2.0 TDI 4Motion",
    engine: "2.0L Dizel",
    hp: 150,
    trans: "Otomatik",
    fuel: "Dizel",
    price: 2499000,
  },
  {
    brand: "Volkswagen",
    model: "Passat",
    version: "1.5 TSI Life",
    engine: "1.5L Turbo",
    hp: 150,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1999000,
  },
  {
    brand: "Volkswagen",
    model: "Arteon",
    version: "2.0 TSI",
    engine: "2.0L Turbo",
    hp: 190,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 2750000,
  },
  {
    brand: "Volkswagen",
    model: "Touareg",
    version: "3.0 V6 TDI",
    engine: "3.0L Dizel",
    hp: 286,
    trans: "Otomatik",
    fuel: "Dizel",
    price: 4500000,
  },
  {
    brand: "Volkswagen",
    model: "ID.3",
    version: "Pro",
    engine: "Elektrik",
    hp: 204,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 1790000,
  },
  {
    brand: "Volkswagen",
    model: "ID.5",
    version: "Pro",
    engine: "Elektrik",
    hp: 204,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 2590000,
  },

  // HYUNDAI
  {
    brand: "Hyundai",
    model: "i10",
    version: "1.2 MPI Select",
    engine: "1.2L",
    hp: 83,
    trans: "Manuel",
    fuel: "Benzin",
    price: 699000,
  },
  {
    brand: "Hyundai",
    model: "i10",
    version: "1.2 MPI Style",
    engine: "1.2L",
    hp: 83,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 849000,
  },
  {
    brand: "Hyundai",
    model: "i20",
    version: "1.4 MPI Select",
    engine: "1.4L",
    hp: 100,
    trans: "Manuel",
    fuel: "Benzin",
    price: 899000,
  },
  {
    brand: "Hyundai",
    model: "i20",
    version: "1.4 MPI Style",
    engine: "1.4L",
    hp: 100,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1049000,
  },
  {
    brand: "Hyundai",
    model: "i20",
    version: "1.0 T-GDI N Line",
    engine: "1.0L Turbo",
    hp: 120,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1249000,
  },
  {
    brand: "Hyundai",
    model: "Tucson",
    version: "1.6 TGDI",
    engine: "1.6L Turbo",
    hp: 160,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1899000,
  },
  {
    brand: "Hyundai",
    model: "Tucson",
    version: "1.6 CRDi",
    engine: "1.6L Dizel",
    hp: 136,
    trans: "Otomatik",
    fuel: "Dizel",
    price: 2099000,
  },
  {
    brand: "Hyundai",
    model: "Santa Fe",
    version: "2.2 CRDi",
    engine: "2.2L Dizel",
    hp: 194,
    trans: "Otomatik",
    fuel: "Dizel",
    price: 3499000,
  },
  {
    brand: "Hyundai",
    model: "Kona",
    version: "1.0 T-GDI",
    engine: "1.0L Turbo",
    hp: 120,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1349000,
  },
  {
    brand: "Hyundai",
    model: "Kona Electric",
    version: "48 kWh",
    engine: "Elektrik",
    hp: 156,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 1799000,
  },
  {
    brand: "Hyundai",
    model: "Ioniq 5",
    version: "58 kWh",
    engine: "Elektrik",
    hp: 170,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 1890000,
  },
  {
    brand: "Hyundai",
    model: "Ioniq 6",
    version: "77 kWh",
    engine: "Elektrik",
    hp: 229,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 2290000,
  },

  // PEUGEOT
  {
    brand: "Peugeot",
    model: "208",
    version: "1.2 PureTech Active",
    engine: "1.2L Turbo",
    hp: 100,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1099000,
  },
  {
    brand: "Peugeot",
    model: "208",
    version: "1.2 PureTech Allure",
    engine: "1.2L Turbo",
    hp: 130,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1299000,
  },
  {
    brand: "Peugeot",
    model: "308",
    version: "1.2 PureTech Active",
    engine: "1.2L Turbo",
    hp: 130,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1399000,
  },
  {
    brand: "Peugeot",
    model: "308",
    version: "1.5 BlueHDi",
    engine: "1.5L Dizel",
    hp: 130,
    trans: "Otomatik",
    fuel: "Dizel",
    price: 1599000,
  },
  {
    brand: "Peugeot",
    model: "2008",
    version: "1.2 PureTech Active",
    engine: "1.2L Turbo",
    hp: 100,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1249000,
  },
  {
    brand: "Peugeot",
    model: "2008",
    version: "1.2 PureTech Allure",
    engine: "1.2L Turbo",
    hp: 130,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1449000,
  },
  {
    brand: "Peugeot",
    model: "3008",
    version: "1.2 PureTech GT",
    engine: "1.2L Turbo",
    hp: 130,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1899000,
  },
  {
    brand: "Peugeot",
    model: "508",
    version: "1.6 Hybrid",
    engine: "1.6L Hybrid",
    hp: 225,
    trans: "Otomatik",
    fuel: "Hibrit",
    price: 2290000,
  },

  // FORD
  {
    brand: "Ford",
    model: "Fiesta",
    version: "1.1 Ti-VCT",
    engine: "1.1L",
    hp: 75,
    trans: "Manuel",
    fuel: "Benzin",
    price: 699000,
  },
  {
    brand: "Ford",
    model: "Puma",
    version: "1.0 EcoBoost Titanium",
    engine: "1.0L Turbo",
    hp: 125,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1514000,
  },
  {
    brand: "Ford",
    model: "Puma",
    version: "1.0 EcoBoost ST",
    engine: "1.0L Turbo",
    hp: 155,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1799000,
  },
  {
    brand: "Ford",
    model: "Focus",
    version: "1.0 EcoBoost Titanium",
    engine: "1.0L Turbo",
    hp: 125,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1399000,
  },
  {
    brand: "Ford",
    model: "Focus",
    version: "2.0 EcoBlue",
    engine: "2.0L Dizel",
    hp: 150,
    trans: "Otomatik",
    fuel: "Dizel",
    price: 1699000,
  },
  {
    brand: "Ford",
    model: "Kuga",
    version: "1.5 EcoBoost Titanium",
    engine: "1.5L Turbo",
    hp: 150,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1799000,
  },
  {
    brand: "Ford",
    model: "Kuga",
    version: "2.0 EcoBlue",
    engine: "2.0L Dizel",
    hp: 190,
    trans: "Otomatik",
    fuel: "Dizel",
    price: 2199000,
  },
  {
    brand: "Ford",
    model: "Explorer",
    version: "2.0 EcoBlue",
    engine: "2.0L Dizel",
    hp: 190,
    trans: "Otomatik",
    fuel: "Dizel",
    price: 2499000,
  },
  {
    brand: "Ford",
    model: "Explorer EV",
    version: "Select",
    engine: "Elektrik",
    hp: 170,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 1720000,
  },
  {
    brand: "Ford",
    model: "Mustang",
    version: "2.3 EcoBoost",
    engine: "2.3L Turbo",
    hp: 304,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 3499000,
  },

  // SKODA
  {
    brand: "Skoda",
    model: "Fabia",
    version: "1.0 MPI",
    engine: "1.0L",
    hp: 80,
    trans: "Manuel",
    fuel: "Benzin",
    price: 899000,
  },
  {
    brand: "Skoda",
    model: "Scala",
    version: "1.0 TSI",
    engine: "1.0L Turbo",
    hp: 95,
    trans: "Manuel",
    fuel: "Benzin",
    price: 1099000,
  },
  {
    brand: "Skoda",
    model: "Scala",
    version: "1.5 TSI",
    engine: "1.5L Turbo",
    hp: 150,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1449000,
  },
  {
    brand: "Skoda",
    model: "Octavia",
    version: "1.5 TSI",
    engine: "1.5L Turbo",
    hp: 150,
    trans: "Manuel",
    fuel: "Benzin",
    price: 1499000,
  },
  {
    brand: "Skoda",
    model: "Octavia",
    version: "1.5 TSI Style",
    engine: "1.5L Turbo",
    hp: 150,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1649000,
  },
  {
    brand: "Skoda",
    model: "Octavia",
    version: "2.0 TDI Style",
    engine: "2.0L Dizel",
    hp: 150,
    trans: "Otomatik",
    fuel: "Dizel",
    price: 1899000,
  },
  {
    brand: "Skoda",
    model: "Karoq",
    version: "1.5 TSI",
    engine: "1.5L Turbo",
    hp: 150,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1749000,
  },
  {
    brand: "Skoda",
    model: "Karoq",
    version: "2.0 TDI",
    engine: "2.0L Dizel",
    hp: 150,
    trans: "Otomatik",
    fuel: "Dizel",
    price: 1999000,
  },
  {
    brand: "Skoda",
    model: "Kodiaq",
    version: "1.5 TSI",
    engine: "1.5L Turbo",
    hp: 150,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 2199000,
  },
  {
    brand: "Skoda",
    model: "Enyaq",
    version: "60",
    engine: "Elektrik",
    hp: 180,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 1950000,
  },

  // OPEL
  {
    brand: "Opel",
    model: "Corsa",
    version: "1.2 Edition",
    engine: "1.2L",
    hp: 75,
    trans: "Manuel",
    fuel: "Benzin",
    price: 989000,
  },
  {
    brand: "Opel",
    model: "Corsa",
    version: "1.2 GS",
    engine: "1.2L Turbo",
    hp: 100,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1149000,
  },
  {
    brand: "Opel",
    model: "Corsa",
    version: "1.2 GS Ultimate",
    engine: "1.2L Turbo",
    hp: 130,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1349000,
  },
  {
    brand: "Opel",
    model: "Astra",
    version: "1.2 GS",
    engine: "1.2L Turbo",
    hp: 130,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1349000,
  },
  {
    brand: "Opel",
    model: "Astra",
    version: "1.5 Diesel",
    engine: "1.5L Dizel",
    hp: 130,
    trans: "Otomatik",
    fuel: "Dizel",
    price: 1599000,
  },
  {
    brand: "Opel",
    model: "Mokka",
    version: "1.2 GS",
    engine: "1.2L Turbo",
    hp: 100,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1249000,
  },
  {
    brand: "Opel",
    model: "Grandland",
    version: "1.2 GS",
    engine: "1.2L Turbo",
    hp: 130,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1549000,
  },
  {
    brand: "Opel",
    model: "Grandland",
    version: "1.6 Hybrid",
    engine: "1.6L Hybrid",
    hp: 225,
    trans: "Otomatik",
    fuel: "Hibrit",
    price: 2199000,
  },

  // KIA
  {
    brand: "Kia",
    model: "Picanto",
    version: "1.2 MT",
    engine: "1.2L",
    hp: 84,
    trans: "Manuel",
    fuel: "Benzin",
    price: 699000,
  },
  {
    brand: "Kia",
    model: "Picanto",
    version: "1.2 AT",
    engine: "1.2L",
    hp: 84,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 849000,
  },
  {
    brand: "Kia",
    model: "Rio",
    version: "1.4 MT",
    engine: "1.4L",
    hp: 100,
    trans: "Manuel",
    fuel: "Benzin",
    price: 899000,
  },
  {
    brand: "Kia",
    model: "Rio",
    version: "1.4 AT",
    engine: "1.4L",
    hp: 100,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1049000,
  },
  {
    brand: "Kia",
    model: "Sportage",
    version: "1.6 T-GDI",
    engine: "1.6L Turbo",
    hp: 177,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1899000,
  },
  {
    brand: "Kia",
    model: "Sportage",
    version: "1.6 CRDi",
    engine: "1.6L Dizel",
    hp: 136,
    trans: "Otomatik",
    fuel: "Dizel",
    price: 2099000,
  },
  {
    brand: "Kia",
    model: "Sorento",
    version: "1.6 T-GDI Hybrid",
    engine: "1.6L Hybrid",
    hp: 230,
    trans: "Otomatik",
    fuel: "Hibrit",
    price: 2899000,
  },
  {
    brand: "Kia",
    model: "EV6",
    version: "2WD",
    engine: "Elektrik",
    hp: 229,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 2699000,
  },
  {
    brand: "Kia",
    model: "Niro",
    version: "1.6 Hybrid",
    engine: "1.6L Hybrid",
    hp: 139,
    trans: "Otomatik",
    fuel: "Hibrit",
    price: 1390000,
  },

  // TOGG
  {
    brand: "Togg",
    model: "T10X",
    version: "V1 RWD Standart",
    engine: "Elektrik",
    hp: 218,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 1505000,
  },
  {
    brand: "Togg",
    model: "T10X",
    version: "V2 RWD",
    engine: "Elektrik",
    hp: 218,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 1598000,
  },
  {
    brand: "Togg",
    model: "T10X",
    version: "V2 RWD Long Range",
    engine: "Elektrik",
    hp: 320,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 1995000,
  },
  {
    brand: "Togg",
    model: "T10X",
    version: "V1 4x4",
    engine: "Elektrik",
    hp: 320,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 2195000,
  },
  {
    brand: "Togg",
    model: "T10F",
    version: "V1 RWD",
    engine: "Elektrik",
    hp: 218,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 1878000,
  },
  {
    brand: "Togg",
    model: "T10F",
    version: "V2 RWD",
    engine: "Elektrik",
    hp: 320,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 2198000,
  },

  // TESLA
  {
    brand: "Tesla",
    model: "Model 3",
    version: "RWD",
    engine: "Elektrik",
    hp: 271,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 2194000,
  },
  {
    brand: "Tesla",
    model: "Model 3",
    version: "Long Range",
    engine: "Elektrik",
    hp: 425,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 2694000,
  },
  {
    brand: "Tesla",
    model: "Model 3",
    version: "Performance",
    engine: "Elektrik",
    hp: 500,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 2994000,
  },
  {
    brand: "Tesla",
    model: "Model Y",
    version: "RWD",
    engine: "Elektrik",
    hp: 245,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 2394000,
  },
  {
    brand: "Tesla",
    model: "Model Y",
    version: "Long Range",
    engine: "Elektrik",
    hp: 384,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 2994000,
  },
  {
    brand: "Tesla",
    model: "Model Y",
    version: "Performance",
    engine: "Elektrik",
    hp: 534,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 3494000,
  },

  // BMW
  {
    brand: "BMW",
    model: "1 Serisi",
    version: "118i",
    engine: "1.5L Turbo",
    hp: 136,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1650000,
  },
  {
    brand: "BMW",
    model: "1 Serisi",
    version: "120i",
    engine: "2.0L Turbo",
    hp: 178,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1950000,
  },
  {
    brand: "BMW",
    model: "3 Serisi",
    version: "320i",
    engine: "2.0L Turbo",
    hp: 156,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 2450000,
  },
  {
    brand: "BMW",
    model: "3 Serisi",
    version: "330i",
    engine: "2.0L Turbo",
    hp: 245,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 2950000,
  },
  {
    brand: "BMW",
    model: "X1",
    version: "sDrive18i",
    engine: "1.5L Turbo",
    hp: 136,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 2150000,
  },
  {
    brand: "BMW",
    model: "X3",
    version: "xDrive20i",
    engine: "2.0L Turbo",
    hp: 184,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 3350000,
  },
  {
    brand: "BMW",
    model: "X5",
    version: "xDrive30d",
    engine: "3.0L Dizel",
    hp: 286,
    trans: "Otomatik",
    fuel: "Dizel",
    price: 4950000,
  },
  {
    brand: "BMW",
    model: "i4",
    version: "eDrive35",
    engine: "Elektrik",
    hp: 286,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 2950000,
  },
  {
    brand: "BMW",
    model: "iX",
    version: "xDrive40",
    engine: "Elektrik",
    hp: 326,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 5500000,
  },

  // MERCEDES
  {
    brand: "Mercedes",
    model: "A Serisi",
    version: "A 180",
    engine: "1.3L Turbo",
    hp: 136,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1750000,
  },
  {
    brand: "Mercedes",
    model: "A Serisi",
    version: "A 200",
    engine: "1.3L Turbo",
    hp: 163,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 2050000,
  },
  {
    brand: "Mercedes",
    model: "C Serisi",
    version: "C 180",
    engine: "1.5L Turbo",
    hp: 170,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 2650000,
  },
  {
    brand: "Mercedes",
    model: "C Serisi",
    version: "C 300",
    engine: "2.0L Turbo",
    hp: 258,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 3450000,
  },
  {
    brand: "Mercedes",
    model: "GLA",
    version: "GLA 180",
    engine: "1.3L Turbo",
    hp: 136,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 2350000,
  },
  {
    brand: "Mercedes",
    model: "GLC",
    version: "GLC 200",
    engine: "2.0L Turbo",
    hp: 197,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 3850000,
  },
  {
    brand: "Mercedes",
    model: "GLE",
    version: "GLE 300",
    engine: "2.0L Turbo",
    hp: 269,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 4950000,
  },

  // AUDI
  {
    brand: "Audi",
    model: "A3",
    version: "35 TFSI",
    engine: "1.5L Turbo",
    hp: 150,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 1850000,
  },
  {
    brand: "Audi",
    model: "A3",
    version: "40 TFSI",
    engine: "2.0L Turbo",
    hp: 190,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 2150000,
  },
  {
    brand: "Audi",
    model: "A4",
    version: "40 TFSI",
    engine: "2.0L Turbo",
    hp: 190,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 2550000,
  },
  {
    brand: "Audi",
    model: "Q3",
    version: "35 TFSI",
    engine: "1.5L Turbo",
    hp: 150,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 2450000,
  },
  {
    brand: "Audi",
    model: "Q5",
    version: "40 TDI",
    engine: "2.0L Dizel",
    hp: 204,
    trans: "Otomatik",
    fuel: "Dizel",
    price: 3850000,
  },
  {
    brand: "Audi",
    model: "Q7",
    version: "45 TDI",
    engine: "3.0L Dizel",
    hp: 231,
    trans: "Otomatik",
    fuel: "Dizel",
    price: 5500000,
  },
  {
    brand: "Audi",
    model: "Q8",
    version: "55 TFSI",
    engine: "3.0L Turbo",
    hp: 340,
    trans: "Otomatik",
    fuel: "Benzin",
    price: 7500000,
  },

  // BYD
  {
    brand: "BYD",
    model: "Dolphin",
    version: "Dynamic",
    engine: "Elektrik",
    hp: 177,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 1299000,
  },
  {
    brand: "BYD",
    model: "Dolphin",
    version: "Premium",
    engine: "Elektrik",
    hp: 204,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 1499000,
  },
  {
    brand: "BYD",
    model: "Seal",
    version: "Premium",
    engine: "Elektrik",
    hp: 313,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 1899000,
  },
  {
    brand: "BYD",
    model: "Seal U",
    version: "Comfort",
    engine: "Elektrik",
    hp: 218,
    trans: "Otomatik",
    fuel: "Elektrik",
    price: 1899000,
  },
];

async function updateAll2025() {
  console.log("\n🔄 TÜM FİYATLAR GÜNCELLENİYOR (2025)...\n");

  let added = 0;
  let updated = 0;

  for (const v of currentPrices2025) {
    try {
      let brand = await prisma.vehicleBrand.findUnique({
        where: { name: v.brand },
      });
      if (!brand) {
        brand = await prisma.vehicleBrand.create({
          data: { name: v.brand, country: "Diğer" },
        });
      }

      let model = await prisma.vehicleModel.findFirst({
        where: { brandId: brand.id, name: v.model },
      });
      if (!model) {
        model = await prisma.vehicleModel.create({
          data: { brandId: brand.id, name: v.model, startYear: 2025 },
        });
      }

      const existing = await prisma.vehicleVersion.findFirst({
        where: { modelId: model.id, name: v.version },
      });

      if (existing) {
        await prisma.vehicleVersion.update({
          where: { id: existing.id },
          data: {
            price: v.price,
            engine: v.engine,
            horsepower: v.hp,
            transmission: v.trans,
            fuel: v.fuel,
            currency: "TL",
            country: "TR",
            source: `${v.brand} Türkiye`,
          },
        });
        updated++;
      } else {
        await prisma.vehicleVersion.create({
          data: {
            modelId: model.id,
            name: v.version,
            engine: v.engine,
            horsepower: v.hp,
            transmission: v.trans,
            fuel: v.fuel,
            price: v.price,
            currency: "TL",
            country: "TR",
            source: `${v.brand} Türkiye`,
          },
        });
        added++;
      }
    } catch (e) {
      // Skip
    }
  }

  console.log(`✓ ${added} yeni eklendi, ${updated} güncellendi`);
  console.log("\n✅ TÜM FİYATLAR GÜNCEL!");

  const brands = await prisma.vehicleBrand.count();
  const models = await prisma.vehicleModel.count();
  const versions = await prisma.vehicleVersion.count();
  console.log(
    `\nToplam: ${brands} marka, ${models} model, ${versions} versiyon`,
  );
}

updateAll2025().finally(() => prisma.$disconnect());
